### ISSUE TITLE
[Bug]can't connect to validator at ac.testnet.libra.org:8000, need to revise the port from 8000 to 80

### ISSUE THREAD

**Issue by friendmine** [libra/libra#139] opened 2019-06-20 03:21 UTC
[Bug]can't connect to validator at ac.testnet.libra.org:8000, need to revise the port from 8000 to 80

**Comment by bothra90** [comment] 2019-06-20 06:51
@friendmine: `8000` still works for me. Could you try again, please?

**Comment by ericnakagawa** [comment] 2019-06-20 21:43
@friendmine I'm going to close this as we can't reproduce. If you still experience this issue, please submit a new issue that includes your system configuration and exact steps to reproduce.

**Closed by ericnakagawa** 2019-06-20 21:43 UTC
Labels: bug

**Comment by zavodil** [comment] 2019-06-26 09:49
Have same issue.
May I register CA file somewhere?

**Comment by php7webmob** [comment] 2019-07-08 07:03
I am facing the same issue:
Running `target/debug/client --host ac.testnet.libra.org --port 8000 -s ./scripts/cli/trusted_peers.config.toml`
Not able to connect to validator at ac.testnet.libra.org:8000, error RpcFailure(RpcStatus { status: DeadlineExceeded, details: Some("Deadline Exceeded") })

**Comment by Johnny-lou** [comment] 2019-12-11 03:26
resolved? @php7webmob

**Comment by php7webmob** [comment] 2019-12-11 04:55
> resolved? @php7webmob

yes.

**Comment by DongfightingABC** [comment] 2019-12-23 09:46
i try to connect the testnet、but the result is error Author is unknown， please help me

**Comment by korrio** [comment] 2020-04-08 03:53
Not able to connect to validator at ac.testnet.libra.org:8000
