### ISSUE TITLE
[Bug] Excceded max mint amount of  1000000000000

### ISSUE THREAD

**Issue by charj** [libra/libra#39] opened 2019-06-18 15:45 UTC
# 🐛 Bug

I tried to transfer a large amount, it got rejected despite me being way within the limit.
Perhaps it's a limitation of testnet but I thought it was worth reporting here.

## To reproduce

** Code snippet to reproduce **
```rust
libra% account mint 1 5200000
```

** Stack trace/error message **
```
[ERROR] Error minting coins: Failed to query remote faucet server[status=400 Bad Request]: "Exceeded max mint amount of 1000000000000"
```

## Expected Behavior
I expect 5200000 to be transferred. Or to receive a message that I have insufficient funds.

## System information

**Please complete the following information:**
- Ubuntu 19.04

**Comment by pierremarsotlyon1** [comment] 2019-06-18 20:27
Duplicate #34

**Comment by kphfb** [comment] 2019-06-19 18:32
Closing since this is a duplicate of #34

**Closed by kphfb** 2019-06-19 18:32 UTC
Labels: bug
