### ISSUE TITLE
[cluster-test]fullnode stay behind validator for more than 5 mins

### ISSUE THREAD

**Issue by snakech** [libra/libra#4649] opened 2020-06-22 17:44 UTC
# 🐛 Bug
We recently catch this bug by new introduced full node health check, which expect all full node recover back to catch up validator within 5 mins after every run of experiment. We do found new failures reported via #push channel, our new full node health check occasionally failed.

**Refer to fullnode health check PR**: 
https://github.com/libra/libra/pull/4591
**Failed job**: 
https://app.circleci.com/pipelines/github/novifinancial/libra-ops/410/workflows/12d8bf7e-2466-47ae-9567-b2a0e8bc6a21/jobs/1831/steps
```INFO 2020-06-22 07:58:02 testsuite/cluster-test/src/main.rs:690 Experiment finished, waiting until all affected validators recover
INFO 2020-06-22 07:58:02 testsuite/cluster-test/src/main.rs:748 Waiting for all nodes to be healthy
INFO 2020-06-22 08:05:58 Experiment `10% down` failed: `Nodes did not become healthy after deployment`
 ```

- Experiment finished at ```07:58:02```, we started full node health check to wait full node catch up the validator.
- At ```08:05:58```, fullnode check failed after 5 mins, ```fn-3-0, fn-12-0``` keep staying behind with validators and stuck.(http://grafana.ct-0-k8s-testnet.aws.hlw3truzy4ls.com/explore?orgId=1&left=%5B%221592811582000%22,%221592813161000%22,%22Prometheus%22,%7B%22expr%22:%22libra_state_sync_committed_version%7Bapp%3D%5C%22libra-fullnode%5C%22%7D%22,%22format%22:%22time_series%22,%22intervalFactor%22:1,%22legendFormat%22:%22%7B%7Bpeer_id%7D%7D%22,%22datasource%22:%22Prometheus%22%7D,%7B%22mode%22:%22Metrics%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D)

looks like fullnode health check found legitimate issue - multiple full nodes did took longer than 5 minutes to catch up, and they were stuck for quite some time, we need to investigate the root cause

## To reproduce

**Code snippet to reproduce**
```rust
# Your code goes here
# Please make sure it does not require any external dependencies
```

**Stack trace/error message**
```
// Paste the output here
```

## System information

**Please complete the following information:**
- 
- 
-

**Comment by andll** [comment] 2020-06-22 21:21
Looks like full node does not start catching up before validator finishes it's initial sync.

Each sync takes about 3 minutes, so total sync time is 6 minutes, which is higher then our original deadline of 5 minutes

**Comment by andll** [comment] 2020-06-23 20:47
One of the thoughts I have about it - do we need to rework state sync so that node catch up concurrently with validator, or should we just assume that in the future full node would just fallback to other validators (and therefor maybe we don't need to change anything)

**Comment by christinacelee** [comment] 2020-06-24 17:50
this is an interesting idea.. I was thinking of reserving fallbacks more to serious upstream failures (upstream node actually goes down / poor network connectivity), since the fallback node will realistically be to publicly advertised VFN, and that would increase competition for traffic. Also we would need on-chain discovery in cluster-test for this 😄

**Comment by andll** [comment] 2020-06-24 17:53
I see. I don't know how hard is to have concurrent state sync, so just floating ideas.
Ideally concurrent state sync is probably good thing to have, as you said, to produce less external traffic

**Comment by christinacelee** [comment] 2020-06-26 22:32
I looked more into this and thought more about it.. I think the state sync for a revived validator and full node will have to be sequential in this scenario. The problem is that when the validator comes back up, it gets an initial ledger info to sync for validator sync, and it syncs on transactions, but those transactions will not be considered committed until all transactions up till the target ledger info are all received. The validator shouldn't serve sync requests for transactions that are not backed by the ledger info during the sync process - only after all the transactions up till the ledger info are received and the ledger info is committed with them can the validator start to serve those transactions to downstream full nodes. So it's a matter of ensuring that an upstream node serves only valid info to the downstream sync requester. 

So it seems like 3 minutes is honestly how long it takes for the validator to catch up on all the transactions it missed out on during the 10% down experiment.

**Comment by christinacelee** [comment] 2020-06-26 22:36
I'm still not convinced whether the VFN in this case should failover to the public VFN, but at least what the downstream client/PFN can do is choose another VFN if it sees it is behind

**Closed** 2020-06-26 22:37 UTC
Labels: bug
