### ISSUE TITLE
Masalah tentang soalan

### ISSUE THREAD

**Issue by Afiqnajmi79** [libra/libra#3751] opened 2020-05-06 14:56 UTC
### Please note that this issue tracker is not a help form and this issue will be closed.

Please contact the development team on [Discourse](https://community.libra.org)

**Comment by bob-wilson** [comment] 2020-05-06 19:08
It is not clear what this issue is about. The title translates to English as "Problems with questions". @Afiqnajmi79 created this and then added the comment saying that this issue would be closed. So, I will close it. If this was intended to report a problem with the Libra system, please clarify.

**Closed by bob-wilson** 2020-05-06 19:08 UTC
