### ISSUE TITLE
Error when start test client

### ISSUE THREAD

**Issue by yoshi721** [libra/libra#181] opened 2019-06-21 21:20 UTC
hey i got the following error message: can anyone help?

Building and running client in debug mode.
   Compiling prost-derive v0.5.0
   Compiling which v2.0.1
   Compiling protoc-grpcio v0.3.1
   Compiling failure_ext v0.1.0 (/root/Desktop/test/libra/libra/common/failure_ext)
   Compiling ed25519-dalek v1.0.0-pre.1
   Compiling threshold_crypto v0.3.1
   Compiling codespan v0.1.3
   Compiling snow v0.5.2
   Compiling network v0.1.0 (/root/Desktop/test/libra/libra/network)
error: failed to run custom build command for `network v0.1.0 (/root/Desktop/test/libra/libra/network)`

Caused by:
  process didn't exit successfully: `/root/Desktop/test/libra/libra/target/debug/build/network-3bce66de4ba49a2b/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=src/proto/network.proto
cargo:rerun-if-changed=src/proto/mempool.proto
cargo:rerun-if-changed=src/proto/consensus.proto

--- stderr
network.proto:4:10: Unrecognized syntax identifier "proto3".  This parser only recognizes "proto2".
thread 'main' panicked at 'protoc: Custom { kind: Other, error: StringError("protoc (\"protoc\" \"-I../types/src/proto\" \"-Isrc/proto\" \"--descriptor_set_out=/tmp/protoc-rustXMd2Vi/descriptor.pbbin\" \"--include_imports\" \"src/proto/network.proto\" \"src/proto/mempool.proto\" \"src/proto/consensus.proto\") exited with non-zero exit code") }', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by 0-o-0** [comment] 2019-06-21 22:43
> network.proto:4:10: Unrecognized syntax identifier "proto3". This parser only recognizes "proto2".

It seems your protoc version is too old. Could you please try to remove the old version and install the latest one?
You can double check by running `protoc --version`, 3.6.0 or above is required.

**Comment by yoshi721** [comment] 2019-06-22 16:02
i tried  protoc --version  -> libprotoc 3.7.0

still the same problem. 

i downloaded the protoc from github und move it to /usr/bin/protoc

is that way correct?

thanks

**Comment by icarter09** [comment] 2019-06-25 20:43
@yoshi721 what OS are you running?

**Comment by ruig2** [comment] 2019-06-26 02:35
I got the same issue with Mac OS X 10.14.5 (18F132).

It seems that I need to uninstall proto2 and re-install proto3. Reference: https://github.com/linkerd/linkerd/issues/1118

I'll post here if this can be fixed with the above reference.

**Comment by ruig2** [comment] 2019-06-26 03:18
The issue is that the default version of `protobuf` in `brew` is 2.x: https://github.com/libra/libra/blob/master/scripts/dev_setup.sh#L141, while we need a 3.x to make things working.

If you get the same issue, let's uninstall `protobuf 2.x` and install a `protobuf 3.x`:

```
brew uninstall protobuf --force # delete 2.x
brew install protobuf@3.6 # install 3.x
protoc --version # it should now show libprotoc 3.6.1
```

Then re-run the scripts (https://developers.libra.org/docs/my-first-transaction) to make Libra working.

**Comment by yoshi721** [comment] 2019-06-26 21:20
> @yoshi721 what OS are you running?

NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

**Comment by katopz** [comment] 2019-06-27 16:58
@yoshi721 work for me https://medium.com/coinmonks/libra-digitalocean-8083326bb266

**Comment by liuzhishan** [comment] 2019-07-28 03:33
@yoshi721 Hi, I have the same problem and I found the solution. You just need to download the protoc (like protoc 3.9.0 from https://github.com/protocolbuffers/protobuf/releases), and copy the include directory to /usr/local.

Just installed protoc 3.6.1 didnt work. I guess installed protoc using brew doesnt copy the include directory to /usr/local, so protoc cannot find them.

**Comment by tommyyama2020** [comment] 2019-11-08 12:13
I am using Mac OS 10.15.1 ver and do not have an issue with the execution of ./scripts/cli/start_cli_testnet.sh. 

have you downloaded the latest one and execute the same?

**Comment by bmwill** [comment] 2020-01-21 19:44
The external dependencies needed to build Libra have been simplified and should only require Rust now so this shouldn't be an issue anymore on master. If it is, please let us know.

**Closed by bmwill** 2020-01-21 19:44 UTC
