### ISSUE TITLE
[Bug] My Libra Coins Just Got Confiscated By a Third Party

### ISSUE THREAD

**Issue by pigd0g** [libra/libra#102] opened 2019-06-19 10:12 UTC
# 🐛 Bug

Funds have been seized by a third party due to violation of terms of service. I just posted something the validators don't agree with on social media.

## To reproduce

Trust facebook with your money.

## Expected Behavior

Be able to do what I want with my money.

**Comment by xmrdsc** [comment] 2019-06-19 10:36
It's a feature not a bug.

**Comment by ZettaScript** [comment] 2019-06-19 10:50
> It's a feature not a bug.

Effectively, so we can say this feature is a bug.

**Comment by lpfloyd** [comment] 2019-06-19 14:29
You win!

**Comment by lucasverra** [comment] 2019-06-19 15:01
keeping this for posterity. M$ do not delete this :)

**Comment by ericnakagawa** [comment] 2019-06-19 17:22
Hi @pigd0g, I'm closing this issue as it appears off-topic.

**Closed by ericnakagawa** 2019-06-19 17:22 UTC
Labels: off-topic

**Comment by fedekunze** [comment] 2019-06-19 19:48
"permissionless" "blockchain"

**Comment by krrisis** [comment] 2019-06-19 19:48
so on-topic!

**Comment by krrisis** [comment] 2019-06-19 19:49
> Hi @pigd0g, I'm closing this issue as it appears off-topic.

so on-topic actually!
