### ISSUE TITLE
[Bug] Inconsistency between storage DB and consensus DB

### ISSUE THREAD

**Issue by aching** [libra/libra#2153] opened 2020-01-03 21:58 UTC
# 🐛 Bug

Node fails to come up - https://gist.github.com/aching/71e495c396c8f5be8538d7fb332af4c3
It looks like storage and consensus can't agree on a block to resume from.

**Comment by lightmark** [comment] 2020-01-07 00:42
@zekun000 do you want close it since it seems not a bug?

**Comment by zekun000** [comment] 2020-01-07 19:24
state sync assumes no empty blocks while the bug fixed by https://github.com/libra/libra/pull/2039 may cause metadata txn fail and result in empty blocks and inconsistency between storage and consensus.

**Closed by zekun000** 2020-01-07 19:24 UTC
Labels: bug, consensus, storage
