### ISSUE TITLE
[Feature Request] Add fixed supply cap

### ISSUE THREAD

**Issue by bitstein** [libra/libra#35] opened 2019-06-18 14:08 UTC
# 🚀 Feature Request

A fixed supply cap would help Libra be a better vehicle for savings and removes inflationary events that could cause disruption to intertemporal market exchanges, which in turn can lead to systemic economic cycles.

## Motivation

Currently, there is no explicit description of the monetary policy of Libra, except an implication that any in-flow of new cash will increase the supply of Libra, as described [here](https://libra.org/en-US/about-currency-reserve/).

## Pitch

Instead of allowing new units to be printed on demand with a new influx of cash, new units should only be allowed to be created at a given rate on a geometric series, which we will call Asymptotic Money Supply Targeting.

Anything else places massive systemic risk on the currency and any economy that uses it. It also gives unfair advantage to well-connected market actors at the expense of less-connected market actors.

Another approach would be to make the reserve solely based on precious metals and cryptocurrencies that do have fixed supply, such as Bitcoin. Otherwise, I fear that Libra will always be in danger of losing relevance to currencies like Bitcoin, because the inflationary model would make it less useful as a vehicle for long term savings and a target for speculative attacks as long as other harder currencies have comparable or better liquidity. I would hate to see the hard work of Libra engineers go completely to waste in the long run, when these technologies offer such hope for not just the next ten years, but the rest of time.

## Additional context

The problems discussed here have been described in endless economic literature over the centuries. The following books should be required reading for Libra developers and association members:

* [The Theory of Money & Credit](https://mises.org/library/theory-money-and-credit) by Ludwig von Mises
* [Money, Bank Credit, and Economic Cycles](https://mises.org/library/money-bank-credit-and-economic-cycles) by Jesús Huerta de Soto
* [The Ethics of Money Production](https://mises.org/library/ethics-money-production) by Jörg Guido Hülsmann

**Comment by irdial** [comment] 2019-06-18 14:11
ACK.

**Comment by kaloudis** [comment] 2019-06-18 14:12
Concept ACK

**Comment by kezown** [comment] 2019-06-18 14:13
Yes!

**Comment by JeffVandrewJr** [comment] 2019-06-18 14:14
A credible monetary policy would go a long way in terms of competing with Ethereum, Ripple, and fiat currencies.

Ending dollar hegemony is a big goal of Mark's, as it's a step closer to his becoming global _Augustus_. This could provide a big boost there.

**Comment by ReneFroger** [comment] 2019-06-18 14:17
ACK.

**Comment by joe-rodgers** [comment] 2019-06-18 14:17
Any definition on Libra's monetary supply will be better than it's fiat counterparts.

If Libra will explicitly say how Libra will be minted, whether on an infinite time schedule or hard cap, that would do wonders to bring confidence.

**Comment by TechniumUnlimited** [comment] 2019-06-18 14:18
> Any definition on Libra's monetary supply will be better than it's fiat counterparts.
> 
> If Libra will explicitly say how Libra will be minted, whether on an infinite time schedule or hard cap, that would do wonders to bring confidence.

It won't be mined, it will be printed, like Tether the coin that is currently under investigation for many crimes by the NY State AG

**Comment by landabaso** [comment] 2019-06-18 14:42
Agree!

**Comment by tangyongzheng** [comment] 2019-06-18 14:47
I don't think it's practical.

**Comment by ipudu** [comment] 2019-06-18 14:52
Since it's a stable coin, why fix supply cap?

**Comment by MrHash** [comment] 2019-06-18 14:54
This is an interesting proposal. Given that there is nothing intrinsically different about a fixed supply vs variable supply cap implementation other than possible variance in subjective value in the market, this sets up a net beneficial regulatory precedent.

**Comment by Kixunil** [comment] 2019-06-18 15:08
ACK

**Comment by dwjorgeb** [comment] 2019-06-18 15:30
Fixed supply leads to it being deflactionary, which leads to speculation and HODLing, which leads to lack of usage as a currency (which is what this is supposed to be) and only as a storage of value...

I don't agree

**Comment by rockstardev** [comment] 2019-06-18 15:33
ACK just for lols.

**Comment by spookiestevie** [comment] 2019-06-18 15:55
👏 Geometric 👏 Monetary 👏 Supply 👏

**Comment by GustavoRSSilva** [comment] 2019-06-18 16:03
ACK

**Comment by FingerCramp** [comment] 2019-06-18 17:04
Of course I agree, and of course it'll never happen since Facebook is a centralized entity we cannot trust.  Obviously the answer is to pivot to bitcoin.

**Comment by dendisuhubdy** [comment] 2019-06-18 17:48
ACK

**Comment by pretyflaco** [comment] 2019-06-18 18:08
ACK

**Comment by Napoleon** [comment] 2019-06-18 19:16
Untested ACK

**Comment by adamtache** [comment] 2019-06-18 19:17
ACK

**Comment by pajasevi** [comment] 2019-06-18 19:18
ACK

**Comment by VinceDot** [comment] 2019-06-18 19:22
Concept ACK

**Comment by gazhayes** [comment] 2019-06-19 01:50
A fixed supply is only relevant or meaningful when coupled with an appropriate level of hard-power decentralisation. Bitcoin was designed to make it impossible to make protocol level changes (like changes to the total supply) without near-unanimous support from everyone involved (primarily, receivers of BTC, not miners). 

This is not the case with Libra. You only need the support of permissioned 'validators'. So even if there was a cap on supply (which would go against the goals of this project), validators can change that cap whenever they want. It's meaningless.

**Comment by Kixunil** [comment] 2019-06-19 07:46
Fixed by #83

**Comment by raymonddurk** [comment] 2019-06-19 09:31
Agreed

**Comment by karozagorus** [comment] 2019-06-19 15:15
ACK. Fix Zuck Bucks

**Comment by bmaurer** [comment] 2019-06-19 21:46
https://libra.org/en-US/about-currency-reserve/ states:

> The association does not set monetary policy. It mints and burns coins only in response to demand from authorized resellers. Users do not need to worry about the association introducing inflation into the system or debasing the currency. For new coins to be minted, there must be a commensurate payment of fiat by resellers into the reserve.

The paper also states why Libra takes this approach:

> Many cryptocurrencies today (e.g., Bitcoin and Ether) have no underlying assets to back them. As a result, speculation and investment have been primary use cases, as with a potential for substantial appreciation many people have acquired these coins hoping to sell them at a higher price later. As beliefs over the longterm value of these currencies and success of their networks fluctuate, so too have their prices, yielding at times massive swings in value.
>
> To drive widespread adoption, Libra is designed to be a currency where any user will know that the value of a Libra today will be close to its value tomorrow and in the future. Just as consumers in Europe know the number of Euros it takes them to buy a coffee today will be similar to the number of Euros it will take them tomorrow, holders of Libra, too, can be confident the value of their coins today will be relatively stable across time.
>
> The reserve is the key mechanism for achieving value preservation. By fully backing each coin with a set of stable and liquid assets (described later) and by working with a competitive group of exchanges and other liquidity providers, users can have confidence that they will be able to sell any Libra coin at or close to the value of the reserve at any time. This gives the coin intrinsic value on day one and helps protect against the speculative swings of other cryptocurrencies. The mechanics of the reserve and the various actors in the system are described later in this section, but, at the outset, it is important to highlight why the reserve was created in the first place — to support stability and value preservation.

**Closed by bmaurer** 2019-06-19 21:46 UTC
Labels: enhancement

**Comment by MrHash** [comment] 2019-06-19 21:51
"This gives the coin intrinsic value." 😄

Good one.

**Comment by likewhoa** [comment] 2019-06-19 22:13
> https://libra.org/en-US/about-currency-reserve/ states:
> 
> > The association does not set monetary policy. It mints and burns coins only in response to demand from authorized resellers. Users do not need to worry about the association introducing inflation into the system or debasing the currency. For new coins to be minted, there must be a commensurate payment of fiat by resellers into the reserve.
> 
> The paper also states why Libra takes this approach:
> 
> > Many cryptocurrencies today (e.g., Bitcoin and Ether) have no underlying assets to back them. As a result, speculation and investment have been primary use cases, as with a potential for substantial appreciation many people have acquired these coins hoping to sell them at a higher price later. As beliefs over the longterm value of these currencies and success of their networks fluctuate, so too have their prices, yielding at times massive swings in value.
> > To drive widespread adoption, Libra is designed to be a currency where any user will know that the value of a Libra today will be close to its value tomorrow and in the future. Just as consumers in Europe know the number of Euros it takes them to buy a coffee today will be similar to the number of Euros it will take them tomorrow, holders of Libra, too, can be confident the value of their coins today will be relatively stable across time.
> > The reserve is the key mechanism for achieving value preservation. By fully backing each coin with a set of stable and liquid assets (described later) and by working with a competitive group of exchanges and other liquidity providers, users can have confidence that they will be able to sell any Libra coin at or close to the value of the reserve at any time. This gives the coin intrinsic value on day one and helps protect against the speculative swings of other cryptocurrencies. The mechanics of the reserve and the various actors in the system are described later in this section, but, at the outset, it is important to highlight why the reserve was created in the first place — to support stability and value preservation.

Unacceptable

**Comment by karozagorus** [comment] 2019-06-20 03:35
> https://libra.org/en-US/about-currency-reserve/ states:
> 
> > The association does not set monetary policy. It mints and burns coins only in response to demand from authorized resellers. Users do not need to worry about the association introducing inflation into the system or debasing the currency. For new coins to be minted, there must be a commensurate payment of fiat by resellers into the reserve.
> 
> The paper also states why Libra takes this approach:
> 
> > Many cryptocurrencies today (e.g., Bitcoin and Ether) have no underlying assets to back them. As a result, speculation and investment have been primary use cases, as with a potential for substantial appreciation many people have acquired these coins hoping to sell them at a higher price later. As beliefs over the longterm value of these currencies and success of their networks fluctuate, so too have their prices, yielding at times massive swings in value.
> > To drive widespread adoption, Libra is designed to be a currency where any user will know that the value of a Libra today will be close to its value tomorrow and in the future. Just as consumers in Europe know the number of Euros it takes them to buy a coffee today will be similar to the number of Euros it will take them tomorrow, holders of Libra, too, can be confident the value of their coins today will be relatively stable across time.
> > The reserve is the key mechanism for achieving value preservation. By fully backing each coin with a set of stable and liquid assets (described later) and by working with a competitive group of exchanges and other liquidity providers, users can have confidence that they will be able to sell any Libra coin at or close to the value of the reserve at any time. This gives the coin intrinsic value on day one and helps protect against the speculative swings of other cryptocurrencies. The mechanics of the reserve and the various actors in the system are described later in this section, but, at the outset, it is important to highlight why the reserve was created in the first place — to support stability and value preservation.

You are stupid because there is an underlying Human consensus that is backing Bitcoin's monetary value, Bitcoin is the hardest form of money to ever exist because of its very high stock to flow ratio, nobody can create more Bitcoins out of thin air without raising the difficulty level. Also you sound like some real shitcoiner who will be facing a lot of crap in the coming years. All I can say is that you guys created a shitcoin here that will be facing an uphill battle to compete against a global, uncensorable currency that can not be impeded upon by ANY government, any LAW, any PERSON. If a government would attempt to ban Bitcoin users can start using the Tor network, use Satellites or RF Radio Communication tools to transact Bitcoins with other users. Libra will be possible to censor to hell, it is not a sound money just another form of monopoly money that is printed out of nowhere. Bitcoin have value because it have a real use case as a payment tool, people keep it because they see value in it and because you don't understand it because you live in a cute little bubble with a comfortable life does not mean that it is not true, you just totally fail to see it and you ignorance will lead yourself to your own doom, so better get used to chewing on foodstamps because in 10 years you will be eating those while standing in line fore government food once the USD goes through a catastrophic hyperinflationary collapse. When it happens, I will come back to this post here and laugh at you because a Master Student have told you the truth and you didn't have the brains to listen to him who was telling you the hard facts. So yeah, fuck you man.

**Comment by gazhayes** [comment] 2019-06-20 03:49
@bmaurer none of that appears to be enforced at the protocol level, am I mistaken about that? 

It doesn't matter what the **intention** is, or how they **say** it will work. What matters is the consensus protocol - mathematics and cryptography.

**Comment by gazhayes** [comment] 2019-06-20 03:53
@karozagorus the personal attacks only distract from your (valid) points. It doesn't help. I really wish you wouldn't do that.

**Comment by bmaurer** [comment] 2019-06-20 06:44
@gazhayes -- until fiat is issued on-chain, you're right that this can't be enforced at the protocol level. However, given this constraint the reserve will be operated in a way to maximize trust:

> The reserve will be held by a geographically distributed network of custodians with investment-grade credit rating to limit counterparty risk. Safeguarding the reserve’s assets, providing high auditability and transparency, avoiding the risks of a centralized reserve, and achieving operational efficiency are the key parameters in custody selection and design.

This is something we're putting a lot of thought into and have a really awesome group of people working on putting it together.

We extensively reviewed options against our primary constraint low-volatility. This was the best option we found.

**Comment by spookiestevie** [comment] 2019-06-20 08:49
@bmaurer can you comment on as to what extent libra is a free & open borderless money? 
If i am not mistaken, the trade-off you are going with is a distributed reserve to minimize volatility rather than protocol level monetary policy verifiable by anyone and everyone. As this is the case, how do you intend to ensure that this money is unseizable, unmanipulatable and censorship resistant from bad actors to give users STRONG confidence their libra will not be seized for any reason.
Thank you for working on this problem, excited for the future of money!

**Comment by likewhoa** [comment] 2019-06-20 14:38
> > The reserve will be held by a geographically distributed network of custodians with investment-grade credit rating to limit counterparty risk. Safeguarding the reserve’s assets, providing high auditability and transparency, avoiding the risks of a centralized reserve, and achieving operational efficiency are the key parameters in custody selection and design.
> 

a geographically distributed network of custodians even with high credit rating (like that matters) can avoid the risks of a centralized reserve when in fact that's what the reserve will be and nothing more. You want operational efficiency you need to be a decentralized reserve that is only move by consensus of node operators as a whole and not by paid validators as you call them. 

I fail to see how this whole model can be good long term. It's basically just a bunch of corporations with other interest that you expect people to trust with their capital.

**Comment by FingerCramp** [comment] 2019-06-20 14:43
@bmaurer will I be free to send any amount of libra to Iran or Russia, instantly, without permission or tracking from any entity?
