### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by rakeshjha2k6** [libra/libra#747] opened 2019-08-28 13:20 UTC
# 🐛 Bug

following the below link , it run “cargo run -p libra_swarm – -s” for Local network.
Link :“https://medium.com/featly/how-to-compile-and-deploy-move-transaction-script-on-libra-local-network-4b03e0ff5cbd”
even though i am getting the issue as below :–
4. Building transaction

 transaction_builder <sender> <sequence_number> <program> <output> --args <payee> <amount>
ubuntu@ip-172-31-7-79:~/libra$ ./target/debug/transaction_builder 225f4e74824d4d5c77f3d692101f1d29e8a67656b9b95f3ca85446f94dbdc3ff 0 ./test/out.program out.txn --args 0x375d048ab6ba861852f44b45c6e7554c5d2e4998ceaa0638cbcbd89d506fbed8 10 – Successful
5. Sending transaction
submitb <path_to_raw_transaction>

libra% dev publish 0x225f4e74824d4d5c77f3d692101f1d29e8a67656b9b95f3ca85446f94dbdc3ff out.txn
invalid escape at line 2 column 10 ----- error message
libra% dev publish 0x225f4e74824d4d5c77f3d692101f1d29e8a67656b9b95f3ca85446f94dbdc3ff /home/ubuntu/libra/out.txn
invalid escape at line 2 column 10 ---- error message

Can u help me regarding this please ?
we can reach on 9538905728 for more detail information.

Regards,
Rakesh kumar Jha

**Comment by bmwill** [comment] 2020-01-21 19:57
I can't reproduce this, but it may be fixed with the latest master.

**Closed by bmwill** 2020-01-21 19:57 UTC
Labels: bug
