### ISSUE TITLE
Where could a distributed setup tool for Libra networks be contributed?

### ISSUE THREAD

**Issue by zmanian** [libra/libra#2252] opened 2020-01-20 23:36 UTC
We( iqlusion/OpenLibra) developed a [tool](https://github.com/open-libra/cli) for doing distributed, asynchronous launches of Libra networks modeled off the Cosmos "gentx" genesis transactions process. This allows parties to asynchronously assemble genesis configuration files, start their nodes and have the network start when quorum(2/3+1) nodes come online. The Open Libra community has started two testnets using this tooling.

We are interested in upstreaming this tool but we would like input from the maintainers about where in the source tree to off it. 

We plan to bring the tool up to date with the current testnet branch sometime this week.

**Comment by davidiw** [comment] 2020-01-22 00:55
Oh wow, this could be interesting. We are definitely interested in improving this area! Have you seen our config/config-builder code? I wonder what additional features you might imagine?

https://github.com/libra/libra/tree/master/config/config-builder

Here's a readme describing it in some depth: https://github.com/libra/libra/tree/master/config/

**Comment by zmanian** [comment] 2020-01-22 05:11
The core problem the openlibra cli is solving right now is that it lets all the validators generate their key material locally. Submit the public keys pairs and then generate the config files for all the validators.

We reverse engineered how to do this from the config builder.

I guess the process could plausibly be integrated into config builder.

**Comment by davidiw** [comment] 2020-01-22 05:40
@zmanian, this sounds really useful, but the documentation is a bit sparse. We have only begun to modestly (and I use that word generously) our production deployment strategy. I'd love to know how it works and your deployment strategy. Do you folks have shareable documentation? If not, perhaps we can organize a VC to chat in more depth.

**Comment by tarcieri** [comment] 2020-01-22 15:17
> Have you seen our config/config-builder code? I wonder what additional features you might imagine?

Our tool is based on `config-builder`, namely large parts of it come from `swarm_config.rs`.

However, we split up the creation of a node/peer's private keys from genesis generation, adding an intermediate `peer_info.toml` file which looks like this:

https://github.com/open-libra/devnet/blob/develop/devnet-1/peer_info_files/iqlusion-0.peer_info.toml

This file contains the peer ID and public keys for a particular node.

The second stage of the tool can take a number of these `peer_info.toml` files and use them to generate `consensus_peers.config.toml`, `network_peers.config.toml`, `seed_peers.config.toml`, and `genesis.blob`.

**Comment by davidiw** [comment] 2020-01-22 18:46
Ahh, that makes sense. We have iterated quite a bit since your tool was developed, so I'd love to see what it looks like given our current state. In terms of placement, I could imagine we could make a new workspace under config called bootstrap. It may make sense for us to also rename config-builder to test-configs or something that implies that it is not a general purpose config builder.

Thinking about your tool, I can imagine
- we distribute this tool to folks
- it populates their favorite service (hsm) with their keys
- generates a public peer config
- submits the peer config to our aggregation service
- they poll the aggregation service waiting for the all peers to submit their information
- receive a genesis and maybe other useful configs from this service

In order for this to work, it would seem we would need to pre-establish identity, so that the aggregation service can distinctly identify a specific validator member and prevent sybils etc etc. We'd also need identity so that validators can ensure they are talking to the correct aggregation service.

Have you modeled this or something like it yet? Or has that part largely been human run?

**Comment by tarcieri** [comment] 2020-01-22 18:49
So far we've done everything through GitHub, and the process has been quite manual: validators open pull requests with their configs, we merge them, and then run the genesis tooling locally once we've merged all the files for a particular devnet.

For what it's worth, this is the workflow used to bootstrap Cosmos and other Tendermint networks and it seems to be fine.

**Comment by davidiw** [comment] 2020-01-22 18:53
That does simplify things a lot! Though it does put a lot of trust into github.

**Comment by tarcieri** [comment] 2020-01-22 18:59
What's nice is validators can check their information is correct in the local repo they clone and also ideally reproduce all of the files themselves to confirm they're properly included and that everyone is seeing the same genesis files.

**Comment by davidiw** [comment] 2020-04-07 05:16
We're starting to ramp up in this space. This conversation was really informative! Any chance you're planning or interested in contributing to this space?

**Comment by tarcieri** [comment] 2020-04-08 18:56
We're continuing to work on a distributed setup tool at:

https://github.com/open-libra/cli

However keeping it up-to-date with upstream has proven quite a chore. See here for the latest work:

https://github.com/open-libra/cli/pull/11

I think it'd definitely be good to have this functionality upstream, and am open to discussing options regarding how it should be designed and who should do the work (which is to say, there are people on the Open Libra side who'd be willing to contribute the functionality if we knew there was actually a path to getting it merged).

**Comment by davidiw** [comment] 2020-09-04 22:53
So we ended up building something leveraging insights from this conversation, see: https://github.com/libra/libra/tree/master/config/management/genesis

much thanks for the helpful and informative conversation!

**Closed by davidiw** 2020-09-04 22:53 UTC
