### ISSUE TITLE
Censorship of the github repo is disturbing

### ISSUE THREAD

**Issue by gazhayes** [libra/libra#135] opened 2019-06-20 00:56 UTC
So, you decided to close #83 which is fine, I would have done the same thing. The intention was to foster debate (and add a bit of humour), not to clog up the PR queue.

But **locking** the discussion itself is something entirely different.

This is almost unheard of in the open source world. The usual practice is to close it and unsubscribe from the thread, not to prevent any further discussion.

This reflects badly on the project itself; it sets the tone and culture of the project.

This isn't about me. I wasn't participating in the discussion itself after the initial post. But many, many other people were making interesting points (both pro and con). By preventing further discussion, you have effectively said that their point of view does not need to be considered, because you know better.

Open discussion is critical to the success of an open source project. You are wrong about things. I am wrong about things. We are all wrong, about most things. But together, through discussion, we error correct. When you prevent discussion because you don't like it, you lose this ability.

**Comment by marcusnewton1** [comment] 2019-06-20 01:39
The code of conduct is copied below. **Bolded text** indicates behaviour that @gazhayes has exhibited:

> Examples of behavior that contributes to creating a positive environment include:
> 
> -    **Using welcoming and inclusive language**
> -    **Being respectful of differing viewpoints and experiences**
> -    **Gracefully accepting constructive criticism**
> -    **Focusing on what is best for the community**
>  -   **Showing empathy towards other community members**
> 
> Examples of unacceptable behavior by participants include:
> 
> -    The use of sexualized language or imagery and unwelcome sexual attention or advances
> -    Trolling, insulting/derogatory comments, and personal or political attacks
> -    Public or private harassment
> -    Publishing others' private information, such as a physical or electronic address, without explicit permission
> -    Other conduct which could reasonably be considered inappropriate in a professional setting

**Comment by notMaven** [comment] 2019-06-20 01:52
You submitted a shitpost level pull request to incite a mass response on their repository.  

What did you expect to happen?  Don't play the woe is me BS and try to play the victim.

**Comment by marcusnewton1** [comment] 2019-06-20 01:56
@notMaven there is potentially a great discussion to be had about how Libra improves on other blockchain technologies while meeting the proposed principles of the Libra white paper. Currently, how Libra will achieve its benevolent goals is unclear and should be subject to further scrutiny.

**Comment by marcusnewton1** [comment] 2019-06-20 01:56
By closing the previous discussion, it indicates that the maintainers are not open to differing viewpoints and experiences.

**Comment by notMaven** [comment] 2019-06-20 01:58
@marcusnewton1 

Submitting a pull request that is purely in the thematic of shitposting is NOT in the spirit of discussion.  It is in the spirit of harassment.  There was no discussion to be created by generating that PR.

**Comment by marcusnewton1** [comment] 2019-06-20 01:58
@notMaven Arguably, it is not purely in the thematic of shitposting. Arguably, it is for the greater good.

**Comment by notMaven** [comment] 2019-06-20 02:00
@marcusnewton1 Submitting a PR with nothing more than a blurb of junk and no constructive criticism, to purely mark delete everything and merge in BTC's code is not for the "greater good".

**Comment by marcusnewton1** [comment] 2019-06-20 02:01
How unfortunate that you see it that way.

**Comment by notMaven** [comment] 2019-06-20 02:01
I would like to point out that the white paper and the technical paper BOTH give direction to a permission less system.  You can knee jerk news respond to everything, but it is clear that you have not read anything and are just following the narrative.

**Comment by notMaven** [comment] 2019-06-20 02:08
> To ensure that Libra is truly open and always operates in the best interest of its users, our ambition is for the Libra network to become permissionless. The challenge is that as of today we do not believe that there is a proven solution that can deliver the scale, stability, and security needed to support billions of people and transactions across the globe through a permissionless network. One of the association’s directives will be to work with the community to research and implement this transition, which will begin within five years of the public launch of the Libra Blockchain and ecosystem.

https://libra.org/en-US/white-paper/#introducing-libra

**Comment by marcusnewton1** [comment] 2019-06-20 02:10
@notMaven Ah yes, with the classical PoS Pareto distribution result: https://medium.com/peercoin/the-rich-get-richer-concept-in-proof-of-stake-systems-82c5ceeff326

**Comment by marcusnewton1** [comment] 2019-06-20 02:11
> The challenge is that as of today we do not believe that there is a proven solution that can deliver the scale, stability, and security needed to support billions of people and transactions across the globe through a permissionless network

Holochain, for one

**Comment by Boycce** [comment] 2019-06-20 02:20
Censorship comes hand and hand with being centralised, but thank-you anyways for giving crypto currencies exposure. Go for it Libra!

**Comment by Boycce** [comment] 2019-06-20 02:22
Censorship comes hand and hand with being centralised, but thank-you anyways for giving crypto currencies exposure. Go for it Libra! :dancer:

**Comment by marcusnewton1** [comment] 2019-06-20 02:36
So don't accept centralisation: https://blog.goodaudience.com/beyond-bitcoin-and-ethereum-a-fairer-and-more-just-post-monetary-sociopolitical-economy-17a8d14de4b0

**Comment by Boycce** [comment] 2019-06-20 02:39
:roll_eyes:

**Comment by 0xSnipe** [comment] 2019-06-20 02:42
#17 got censored

**Comment by karozagorus** [comment] 2019-06-20 03:43
What did you expect from sh!tmunchers like Facebook? It's time to wage a war against them finally.

**Comment by bmaurer** [comment] 2019-06-20 06:34
Hey @gazhayes --

I'm the tech lead on the Calibra team. I was part of the discussion around how we should handle issues like this, so I wanted to provide some context.

In my experience with open source projects, when a issue gets traffic from twitter / etc it often becomes necessary to lock the topic. Otherwise the issue becomes a target of non-thoughtful discussion and project members have to spend time moderating it. It seems from your comments like you are interested in having thoughtful discussion. But your friends on #83 didn't seem as thoughtful.

We could have had a better explanation of our decision to lock the thread. Also, we should have pointed the discussion at the discourse community which is a better place for handling broad conversations. 

Do these seem like reasonable policies? How about we re-purpose this task to come up with guidelines for how to handle these types of tasks that balance the need for moderation with having open discussion?

**Comment by fuhaha** [comment] 2019-06-20 06:40
I agree  your policy.

**Comment by marcusnewton1** [comment] 2019-06-20 06:42
@bmaurer Given we're talking about something that has the potential to completely transform the world, for good and/or for worse, any and all discordance should be taken very seriously, no matter the form it takes.

**Comment by bmaurer** [comment] 2019-06-20 06:50
> @bmaurer Given we're talking about something that has the potential to completely transform the world, for good and/or for worse, any and all discordance should be taken very seriously, no matter the form it takes.

+1. We're really cognizent of the fact that this is a transformative effort and that the we need to build a community around it. That's why Calibra has contributed the project to the Libra Association and why development is happening in the open.

But having discourse doesn't mean the lack of moderation. Off-topic conversations detract from fruitful ones. The thread on #83 was not productive and would have tied up moderation resources. Personally I believe locking was the right call -- I've seen other projects do the same under similar circumstances. But I'd like to hear your take on the best practices.

**Comment by gazhayes** [comment] 2019-06-20 06:54
Hi @bmaurer, thanks for that response, I appreciate it.

> the issue becomes a target of non-thoughtful discussion and project members have to spend time moderating it

> How about we re-purpose this task to come up with guidelines for how to handle these types of tasks that balance the need for moderation with having open discussion?

I disagree with the major unstated premise here that central control of the discussion is necessary, in fact I think this will end up being counter-productive (it generally does). 

The desire to control communications can be difficult to let go of, but it's also the only way that a blockchain project can survive. 

Closing the PR is a sufficient response, it's possible to unsubscribe from notifications on a per-issue/PR basis so it doesn't need to take up the time of anyone who doesn't wish to participate.

> we should have pointed the discussion at the discourse community which is a better place for handling broad conversations

Yes, I think that's fine. And I think the community will be fine with this too, in general, depending on where the lines are drawn.

On my projects, I implement a [protocol](http://socialarchitecture.science/c4/) which clearly describes what is and isn't a valid issue and PR. You may wish to adapt that to suit Libra and help you determine what should be considered appropriate for Github and what's appropriate for the forum.

**Comment by bmaurer** [comment] 2019-06-20 07:01
Thanks for that. The protocol thing is a good idea. One thing that I also think contributed to our decision was that in many bug tracking systems anybody can reopen a closed issue. Looks like this isn’t the case on GitHub. That makes it easier to close the issue and let people unsubscribe themselves. We will discuss and revert on this thread.

I know we may not see eye to eye on some of the approaches Libra has taken but it’s great to see that you’re taking an interest in helping us build a strong community. Hope you’ll stick around — over the year we’ve been working on this project we’ve seen a lot of people with strong beliefs realize that the Libra approach is complementary to existing projects and meets an urgent set of real world needs.

**Closed** 2019-06-20 09:32 UTC

**Comment by rockstardev** [comment] 2019-06-20 18:34
I like your approach and guiding hand so far @bmaurer. I'm not sure how much leeway you have considering constraints of being Facebook project; but as long as transparency is maintained I think this will be fun project to watch. Thanks for all the info and good luck!

**Comment by bmaurer** [comment] 2019-06-20 21:40
Just as an update, we discussed the following guidelines:

Close -- if the issue is off-topic
Lock -- if the issue is on-topic but has been linked from twitter etc (i.e. if the issue should stay open but the influx of comments prevents productive conversation). Or if a closed, off-topic issue doesn't die down and consumes time of forum moderators.
Delete -- if the post contains harassment / illegal content / malware / etc

**Comment by gwestcot** [comment] 2019-06-21 03:38
@bmaurer Who defines if the issue is off-topic? Why would getting more input from people be unproductive? What content on the internet should be illegal? You guys don't fit into this space well do you?
