### ISSUE TITLE
[Bug] Build failed on MacOS Mojave 10.14.5 

### ISSUE THREAD

**Issue by suraneti** [libra/libra#215] opened 2019-06-24 16:34 UTC
# 🐛 Bug

## To reproduce

** Code snippet to reproduce **
```rust
./scripts/cli/start_cli_testnet.sh
```

** Stack trace/error message **
```
Building and running client in debug mode.
   Compiling mempool v0.1.0 (/Users/suraneti/libra/mempool)
   Compiling admission_control_proto v0.1.0 (/Users/suraneti/libra/admission_control/admission_control_proto)
   Compiling types v0.1.0 (/Users/suraneti/libra/types)
error: failed to write `/Users/suraneti/libra/target/debug/.fingerprint/types-cc4e4a0bb3add5b8/invoked.timestamp`

Caused by:
  Permission denied (os error 13)
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `admission_control_proto v0.1.0 (/Users/suraneti/libra/admission_control/admission_control_proto)`

Caused by:
  process didn't exit successfully: `/Users/suraneti/libra/target/debug/build/admission_control_proto-03b3d2126a3ca020/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=../../types/src/proto/vm_errors.proto
cargo:rerun-if-changed=../../types/src/proto/get_with_proof.proto
cargo:rerun-if-changed=../../types/src/proto/events.proto
cargo:rerun-if-changed=../../types/src/proto/account_state_blob.proto
cargo:rerun-if-changed=../../types/src/proto/transaction.proto
cargo:rerun-if-changed=../../types/src/proto/validator_public_keys.proto
cargo:rerun-if-changed=../../types/src/proto/proof.proto
cargo:rerun-if-changed=../../types/src/proto/validator_change.proto
cargo:rerun-if-changed=../../types/src/proto/access_path.proto
cargo:rerun-if-changed=../../types/src/proto/validator_set.proto
cargo:rerun-if-changed=../../types/src/proto/ledger_info.proto
cargo:rerun-if-changed=../../types/src/proto/transaction_info.proto
cargo:rerun-if-changed=../../mempool/src/proto/shared/mempool_status.proto
cargo:rerun-if-changed=src/proto/admission_control.proto

--- stderr
admission_control.proto: No such file or directory
thread 'main' panicked at 'failed to write descriptor set: Custom { kind: Other, error: StringError("protoc (\"protoc\" \"-I../../types/src/proto\" \"-I../../mempool/src/proto/shared\" \"-Isrc/proto\" \"--descriptor_set_out=/var/folders/2b/rjzvbp2n2cv6gqndhycgxg_40000gp/T/18cd9ab64b7047008ba2c140c719d449\" \"--include_imports\" \"admission_control.proto\") exited with non-zero exit code") }', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `mempool v0.1.0 (/Users/suraneti/libra/mempool)`

Caused by:
  process didn't exit successfully: `/Users/suraneti/libra/target/debug/build/mempool-e66c6f51ea4dd9e3/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=src/proto/shared/mempool_status.proto
cargo:rerun-if-changed=../types/src/proto/vm_errors.proto
cargo:rerun-if-changed=../types/src/proto/get_with_proof.proto
cargo:rerun-if-changed=../types/src/proto/events.proto
cargo:rerun-if-changed=../types/src/proto/account_state_blob.proto
cargo:rerun-if-changed=../types/src/proto/transaction.proto
cargo:rerun-if-changed=../types/src/proto/validator_public_keys.proto
cargo:rerun-if-changed=../types/src/proto/proof.proto
cargo:rerun-if-changed=../types/src/proto/validator_change.proto
cargo:rerun-if-changed=../types/src/proto/access_path.proto
cargo:rerun-if-changed=../types/src/proto/validator_set.proto
cargo:rerun-if-changed=../types/src/proto/ledger_info.proto
cargo:rerun-if-changed=../types/src/proto/transaction_info.proto
cargo:rerun-if-changed=src/proto/shared/mempool_status.proto
cargo:rerun-if-changed=src/proto/mempool.proto

--- stderr
mempool.proto: No such file or directory
thread 'main' panicked at 'failed to write descriptor set: Custom { kind: Other, error: StringError("protoc (\"protoc\" \"-I../types/src/proto\" \"-Isrc/proto/shared\" \"-Isrc/proto\" \"--descriptor_set_out=/var/folders/2b/rjzvbp2n2cv6gqndhycgxg_40000gp/T/663d76148653484985ae9c8eae13fa62\" \"--include_imports\" \"mempool.proto\") exited with non-zero exit code") }', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

## Expected Behavior

Build successful

## System information

**Please complete the following information:**
- master branch
- rustc 1.35.0 (3c235d560 2019-05-20)
- MacOS Mojave 10.14.5

**Comment by bmwill** [comment] 2019-06-24 16:42
Looking at your logs this stands out:

> Caused by:
>   Permission denied (os error 13)

You might need to make sure your permissions are set properly on your filesystem for the `libra` directory.

**Comment by suraneti** [comment] 2019-06-24 16:44
@bmwill I've chmod 775 on libra directory but it still failed.

**Comment by bmwill** [comment] 2019-06-24 16:55
Does it fail with the same error message?

**Comment by suraneti** [comment] 2019-06-24 17:00
@bmwill here is a stack trace

```
Suraneti's Macbook Pro:libra suraneti$ ./scripts/cli/start_cli_testnet.sh
Building and running client in debug mode.
   Compiling mempool v0.1.0 (/Users/suraneti/libra/mempool)
   Compiling admission_control_proto v0.1.0 (/Users/suraneti/libra/admission_control/admission_control_proto)
   Compiling types v0.1.0 (/Users/suraneti/libra/types)
error: failed to run custom build command for `admission_control_proto v0.1.0 (/Users/suraneti/libra/admission_control/admission_control_proto)`

Caused by:
  process didn't exit successfully: `/Users/suraneti/libra/target/debug/build/admission_control_proto-03b3d2126a3ca020/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=../../types/src/proto/vm_errors.proto
cargo:rerun-if-changed=../../types/src/proto/get_with_proof.proto
cargo:rerun-if-changed=../../types/src/proto/events.proto
cargo:rerun-if-changed=../../types/src/proto/account_state_blob.proto
cargo:rerun-if-changed=../../types/src/proto/transaction.proto
cargo:rerun-if-changed=../../types/src/proto/validator_public_keys.proto
cargo:rerun-if-changed=../../types/src/proto/proof.proto
cargo:rerun-if-changed=../../types/src/proto/validator_change.proto
cargo:rerun-if-changed=../../types/src/proto/access_path.proto
cargo:rerun-if-changed=../../types/src/proto/validator_set.proto
cargo:rerun-if-changed=../../types/src/proto/ledger_info.proto
cargo:rerun-if-changed=../../types/src/proto/transaction_info.proto
cargo:rerun-if-changed=../../mempool/src/proto/shared/mempool_status.proto
cargo:rerun-if-changed=src/proto/admission_control.proto

--- stderr
admission_control.proto: No such file or directory
thread 'main' panicked at 'failed to write descriptor set: Custom { kind: Other, error: StringError("protoc (\"protoc\" \"-I../../types/src/proto\" \"-I../../mempool/src/proto/shared\" \"-Isrc/proto\" \"--descriptor_set_out=/var/folders/2b/rjzvbp2n2cv6gqndhycgxg_40000gp/T/db0d6aed35664b2eaf272113ae1602bd\" \"--include_imports\" \"admission_control.proto\") exited with non-zero exit code") }', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `mempool v0.1.0 (/Users/suraneti/libra/mempool)`

Caused by:
  process didn't exit successfully: `/Users/suraneti/libra/target/debug/build/mempool-e66c6f51ea4dd9e3/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=src/proto/shared/mempool_status.proto
cargo:rerun-if-changed=../types/src/proto/vm_errors.proto
cargo:rerun-if-changed=../types/src/proto/get_with_proof.proto
cargo:rerun-if-changed=../types/src/proto/events.proto
cargo:rerun-if-changed=../types/src/proto/account_state_blob.proto
cargo:rerun-if-changed=../types/src/proto/transaction.proto
cargo:rerun-if-changed=../types/src/proto/validator_public_keys.proto
cargo:rerun-if-changed=../types/src/proto/proof.proto
cargo:rerun-if-changed=../types/src/proto/validator_change.proto
cargo:rerun-if-changed=../types/src/proto/access_path.proto
cargo:rerun-if-changed=../types/src/proto/validator_set.proto
cargo:rerun-if-changed=../types/src/proto/ledger_info.proto
cargo:rerun-if-changed=../types/src/proto/transaction_info.proto
cargo:rerun-if-changed=src/proto/shared/mempool_status.proto
cargo:rerun-if-changed=src/proto/mempool.proto

--- stderr
mempool.proto: No such file or directory
thread 'main' panicked at 'failed to write descriptor set: Custom { kind: Other, error: StringError("protoc (\"protoc\" \"-I../types/src/proto\" \"-Isrc/proto/shared\" \"-Isrc/proto\" \"--descriptor_set_out=/var/folders/2b/rjzvbp2n2cv6gqndhycgxg_40000gp/T/fe4043f8d96744b69b5cab4ab8f18230\" \"--include_imports\" \"mempool.proto\") exited with non-zero exit code") }', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by volkanunsal** [comment] 2019-06-24 17:18
I'm having the same issue.

**Comment by kphfb** [comment] 2019-06-24 22:19
Let's try building it incrementally and see if we can narrow down the issue.  Can you first do the following:

cd types
cargo build

cd admission_control
cargo build

If that works, then try this again:
./scripts/cli/start_cli_testnet.sh

**Comment by suraneti** [comment] 2019-06-25 01:07
@kphfb cargo build worked on types directory but failed on admission_control directory.

here is error message.

```
Suraneti's Macbook Pro:admission_control suraneti$ cargo build
  Downloaded rayon v1.1.0
  Downloaded backoff v0.1.5
  Downloaded jemallocator v0.1.9
  Downloaded crc v1.8.1
  Downloaded jemalloc-sys v0.1.8
  Downloaded libz-sys v1.0.25
  Downloaded tempdir v0.3.7
  Downloaded glob v0.3.0
  Downloaded assert_matches v1.3.0
  Downloaded getopts v0.2.19
  Downloaded signal-hook v0.1.9
  Downloaded futures-locks v0.3.0
  Downloaded mirai-annotations v0.1.0
  Downloaded num-derive v0.2.5
  Downloaded rmp-serde v0.13.7
  Downloaded datatest v0.3.1
  Downloaded termion v1.5.3
  Downloaded filecheck v0.4.0
  Downloaded termcolor v1.0.5
  Downloaded fs_extra v1.1.0
  Downloaded rayon-core v1.5.0
  Downloaded build_const v0.2.1
  Downloaded rmp v0.8.7
  Downloaded signal-hook-registry v1.0.1
  Downloaded numtoa v0.1.0
  Downloaded serde_yaml v0.8.9
  Downloaded yaml-rust v0.4.3
  Downloaded num-traits v0.1.43
  Downloaded arc-swap v0.3.11
  Downloaded dtoa v0.4.4
  Downloaded datatest-derive v0.3.1
   Compiling rayon-core v1.5.0
   Compiling memchr v2.2.0
   Compiling glob v0.3.0
   Compiling build_const v0.2.1
   Compiling fs_extra v1.1.0
   Compiling num-derive v0.2.5
   Compiling arc-swap v0.3.11
   Compiling numtoa v0.1.0
   Compiling dtoa v0.4.4
   Compiling mirai-annotations v0.1.0
   Compiling assert_matches v1.3.0
   Compiling termcolor v1.0.5
   Compiling testsuite v0.1.0 (/Users/suraneti/libra/testsuite)
   Compiling tools v0.1.0 (/Users/suraneti/libra/common/tools)
   Compiling getopts v0.2.19
   Compiling yaml-rust v0.4.3
   Compiling crc v1.8.1
   Compiling termion v1.5.3
   Compiling signal-hook-registry v1.0.1
   Compiling tempdir v0.3.7
   Compiling num-traits v0.1.43
   Compiling datatest-derive v0.3.1
   Compiling backoff v0.1.5
   Compiling rmp v0.8.7
   Compiling sha-1 v0.8.1
   Compiling signal-hook v0.1.9
   Compiling rusty-fork v0.2.2
   Compiling aho-corasick v0.7.3
   Compiling rustyline v4.1.0
   Compiling futures-util-preview v0.3.0-alpha.16
   Compiling rmp-serde v0.13.7
   Compiling parity-multihash v0.1.2
   Compiling rayon v1.1.0
   Compiling proptest v0.9.4
   Compiling serde_yaml v0.8.9
   Compiling regex v1.1.7
   Compiling parity-multiaddr v0.4.1
   Compiling futures-locks v0.3.0
   Compiling futures-executor-preview v0.3.0-alpha.16
   Compiling cc v1.0.37
   Compiling futures-preview v0.3.0-alpha.16
   Compiling docopt v1.1.0
   Compiling datatest v0.3.1
   Compiling memsocket v0.1.0 (/Users/suraneti/libra/network/memsocket)
   Compiling netcore v0.1.0 (/Users/suraneti/libra/network/netcore)
   Compiling backtrace-sys v0.1.28
   Compiling clear_on_drop v0.2.3
   Compiling cmake v0.1.40
   Compiling ring v0.14.6
   Compiling zstd-sys v1.4.10+zstd.1.4.0 (https://github.com/gyscos/zstd-rs.git#d09a3a06)
   Compiling lz4-sys v1.8.0 (https://github.com/busyjay/lz4-rs.git?branch=adjust-build#41509fea)
   Compiling bzip2-sys v0.1.7 (https://github.com/alexcrichton/bzip2-rs.git#18fd3e18)
   Compiling libz-sys v1.0.25
   Compiling jemalloc-sys v0.1.8
   Compiling grpcio-sys v0.4.4
   Compiling snappy-sys v0.1.0 (https://github.com/busyjay/rust-snappy.git?branch=static-link#8c12738b)
   Compiling libtitan_sys v0.0.1 (https://github.com/pingcap/rust-rocksdb.git?rev=8d6cda70f22da2cd15ed7351fcffa9add3444595#8d6cda70)
   Compiling librocksdb_sys v0.1.0 (https://github.com/pingcap/rust-rocksdb.git?rev=8d6cda70f22da2cd15ed7351fcffa9add3444595#8d6cda70)
   Compiling backtrace v0.3.31
   Compiling curve25519-dalek v1.2.1
   Compiling snow v0.5.2
   Compiling lalrpop v0.16.3
   Compiling failure v0.1.5
   Compiling prost-derive v0.5.0
   Compiling which v2.0.1
   Compiling protoc-grpcio v0.3.1
   Compiling failure_ext v0.1.0 (/Users/suraneti/libra/common/failure_ext)
   Compiling threshold_crypto v0.3.1
   Compiling codespan v0.1.3
   Compiling filecheck v0.4.0
   Compiling prost-build v0.5.0
   Compiling canonical_serialization v0.1.0 (/Users/suraneti/libra/common/canonical_serialization)
   Compiling logger v0.1.0 (/Users/suraneti/libra/common/logger)
   Compiling codespan-reporting v0.1.4
   Compiling prost v0.5.0
   Compiling x25519-dalek v0.5.2
   Compiling ed25519-dalek v1.0.0-pre.1
   Compiling prost-types v0.5.0
   Compiling proptest_helpers v0.1.0 (/Users/suraneti/libra/common/proptest_helpers)
   Compiling jemallocator v0.1.9
   Compiling jemalloc v0.1.0 (/Users/suraneti/libra/common/jemalloc)
   Compiling crash_handler v0.1.0 (/Users/suraneti/libra/common/crash_handler)
   Compiling grpcio-compiler v0.5.0-alpha
   Compiling protoc-grpcio v1.0.2
   Compiling grpcio-client v0.1.0 (/Users/suraneti/libra/common/grpcio-client)
   Compiling build_helpers v0.1.0 (/Users/suraneti/libra/common/build_helpers)
   Compiling proto_conv v0.1.0 (/Users/suraneti/libra/common/proto_conv)
   Compiling types v0.1.0 (/Users/suraneti/libra/types)
   Compiling storage_proto v0.1.0 (/Users/suraneti/libra/storage/storage_proto)
   Compiling mempool v0.1.0 (/Users/suraneti/libra/mempool)
   Compiling execution_proto v0.1.0 (/Users/suraneti/libra/execution/execution_proto)
   Compiling admission_control_proto v0.1.0 (/Users/suraneti/libra/admission_control/admission_control_proto)
   Compiling debug_interface v0.1.0 (/Users/suraneti/libra/common/debug_interface)
   Compiling consensus v0.1.0 (/Users/suraneti/libra/consensus)
   Compiling secret_service v0.1.0 (/Users/suraneti/libra/crypto/secret_service)
error: failed to run custom build command for `mempool v0.1.0 (/Users/suraneti/libra/mempool)`

Caused by:
  process didn't exit successfully: `/Users/suraneti/libra/target/debug/build/mempool-713ece62a57c4fab/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=src/proto/shared/mempool_status.proto
cargo:rerun-if-changed=../types/src/proto/vm_errors.proto
cargo:rerun-if-changed=../types/src/proto/get_with_proof.proto
cargo:rerun-if-changed=../types/src/proto/events.proto
cargo:rerun-if-changed=../types/src/proto/account_state_blob.proto
cargo:rerun-if-changed=../types/src/proto/transaction.proto
cargo:rerun-if-changed=../types/src/proto/validator_public_keys.proto
cargo:rerun-if-changed=../types/src/proto/proof.proto
cargo:rerun-if-changed=../types/src/proto/validator_change.proto
cargo:rerun-if-changed=../types/src/proto/access_path.proto
cargo:rerun-if-changed=../types/src/proto/validator_set.proto
cargo:rerun-if-changed=../types/src/proto/ledger_info.proto
cargo:rerun-if-changed=../types/src/proto/transaction_info.proto
cargo:rerun-if-changed=src/proto/shared/mempool_status.proto
cargo:rerun-if-changed=src/proto/mempool.proto

--- stderr
mempool.proto: No such file or directory
thread 'main' panicked at 'failed to write descriptor set: Custom { kind: Other, error: StringError("protoc (\"protoc\" \"-I../types/src/proto\" \"-Isrc/proto/shared\" \"-Isrc/proto\" \"--descriptor_set_out=/var/folders/2b/rjzvbp2n2cv6gqndhycgxg_40000gp/T/c18d8e945e1b4701906558729a06676c\" \"--include_imports\" \"mempool.proto\") exited with non-zero exit code") }', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
    Building [==============================================>        ] 495/570: librocksdb_sys(build)                                                                               

error: build failed
```

**Comment by suraneti** [comment] 2019-06-25 04:01
Problem seem to be solved after I've upgrade `protobuf 3.0.0-beta-4 -> 3.7.1` via brew  
[Installing protoc](http://google.github.io/proto-lens/installing-protoc.html)

**Comment by vjoke** [comment] 2019-06-25 05:47
I have the same issue, solved with #90

**Comment by 4ntoine** [comment] 2019-07-03 20:14
i've updated protobuf from 3.4.1 to 3.7.1 but it did not help:
```
~/Documents/dev/src/libra asmirnov$./scripts/cli/start_cli_testnet.sh
Building and running client in debug mode.
   Compiling mempool v0.1.0 (/Users/asmirnov/Documents/dev/src/libra/mempool)
   Compiling admission_control_proto v0.1.0 (/Users/asmirnov/Documents/dev/src/libra/admission_control/admission_control_proto)
   Compiling types v0.1.0 (/Users/asmirnov/Documents/dev/src/libra/types)
   Compiling noise v0.1.0 (/Users/asmirnov/Documents/dev/src/libra/network/noise)
error: failed to run custom build command for `admission_control_proto v0.1.0 (/Users/asmirnov/Documents/dev/src/libra/admission_control/admission_control_proto)`

Caused by:
  process didn't exit successfully: `/Users/asmirnov/Documents/dev/src/libra/target/debug/build/admission_control_proto-dd0751614cffc296/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=../../types/src/proto/vm_errors.proto
cargo:rerun-if-changed=../../types/src/proto/get_with_proof.proto
cargo:rerun-if-changed=../../types/src/proto/events.proto
cargo:rerun-if-changed=../../types/src/proto/account_state_blob.proto
cargo:rerun-if-changed=../../types/src/proto/language_storage.proto
cargo:rerun-if-changed=../../types/src/proto/transaction.proto
cargo:rerun-if-changed=../../types/src/proto/validator_public_keys.proto
cargo:rerun-if-changed=../../types/src/proto/proof.proto
cargo:rerun-if-changed=../../types/src/proto/validator_change.proto
cargo:rerun-if-changed=../../types/src/proto/access_path.proto
cargo:rerun-if-changed=../../types/src/proto/validator_set.proto
cargo:rerun-if-changed=../../types/src/proto/ledger_info.proto
cargo:rerun-if-changed=../../types/src/proto/transaction_info.proto
cargo:rerun-if-changed=../../mempool/src/proto/shared/mempool_status.proto
cargo:rerun-if-changed=src/proto/admission_control.proto

--- stderr
admission_control.proto: No such file or directory
thread 'main' panicked at 'failed to write descriptor set: Custom { kind: Other, error: StringError("protoc (\"protoc\" \"-I../../types/src/proto\" \"-I../../mempool/src/proto/shared\" \"-Isrc/proto\" \"--descriptor_set_out=/var/folders/_l/kl9pdj2x50v7416j8htb6w740000gn/T/c7427b5c33bf4dd88d1f4a9cbc63d848\" \"--include_imports\" \"admission_control.proto\") exited with non-zero exit code") }', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `mempool v0.1.0 (/Users/asmirnov/Documents/dev/src/libra/mempool)`

Caused by:
  process didn't exit successfully: `/Users/asmirnov/Documents/dev/src/libra/target/debug/build/mempool-b7276e1e81655bbc/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=src/proto/shared/mempool_status.proto
cargo:rerun-if-changed=../types/src/proto/vm_errors.proto
cargo:rerun-if-changed=../types/src/proto/get_with_proof.proto
cargo:rerun-if-changed=../types/src/proto/events.proto
cargo:rerun-if-changed=../types/src/proto/account_state_blob.proto
cargo:rerun-if-changed=../types/src/proto/language_storage.proto
cargo:rerun-if-changed=../types/src/proto/transaction.proto
cargo:rerun-if-changed=../types/src/proto/validator_public_keys.proto
cargo:rerun-if-changed=../types/src/proto/proof.proto
cargo:rerun-if-changed=../types/src/proto/validator_change.proto
cargo:rerun-if-changed=../types/src/proto/access_path.proto
cargo:rerun-if-changed=../types/src/proto/validator_set.proto
cargo:rerun-if-changed=../types/src/proto/ledger_info.proto
cargo:rerun-if-changed=../types/src/proto/transaction_info.proto
cargo:rerun-if-changed=src/proto/shared/mempool_status.proto
cargo:rerun-if-changed=src/proto/mempool.proto

--- stderr
mempool.proto: No such file or directory
thread 'main' panicked at 'failed to write descriptor set: Custom { kind: Other, error: StringError("protoc (\"protoc\" \"-I../types/src/proto\" \"-Isrc/proto/shared\" \"-Isrc/proto\" \"--descriptor_set_out=/var/folders/_l/kl9pdj2x50v7416j8htb6w740000gn/T/a29e5ca01d284a59a514b508f7a91113\" \"--include_imports\" \"mempool.proto\") exited with non-zero exit code") }', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed

```

**Comment by suraneti** [comment] 2019-07-04 04:04
@4ntoine can you try to building with this instruction by @kphfb, and see issue.
> Let's try building it incrementally and see if we can narrow down the issue. Can you first do the following:
> 
> cd types
> cargo build
> 
> cd admission_control
> cargo build
> 
> If that works, then try this again:
> ./scripts/cli/start_cli_testnet.sh

**Comment by 4ntoine** [comment] 2019-07-05 19:42
```
cd admission_control
cargo build
```
failed:
```
   Compiling consensus v0.1.0 (/Users/asmirnov/Documents/dev/src/libra/consensus)
   Compiling secret_service v0.1.0 (/Users/asmirnov/Documents/dev/src/libra/crypto/secret_service)
error: failed to run custom build command for `mempool v0.1.0 (/Users/asmirnov/Documents/dev/src/libra/mempool)`

Caused by:
  process didn't exit successfully: `/Users/asmirnov/Documents/dev/src/libra/target/debug/build/mempool-36303eba014e6396/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=src/proto/shared/mempool_status.proto
cargo:rerun-if-changed=../types/src/proto/vm_errors.proto
cargo:rerun-if-changed=../types/src/proto/get_with_proof.proto
cargo:rerun-if-changed=../types/src/proto/events.proto
cargo:rerun-if-changed=../types/src/proto/account_state_blob.proto
cargo:rerun-if-changed=../types/src/proto/language_storage.proto
cargo:rerun-if-changed=../types/src/proto/transaction.proto
cargo:rerun-if-changed=../types/src/proto/validator_public_keys.proto
cargo:rerun-if-changed=../types/src/proto/proof.proto
cargo:rerun-if-changed=../types/src/proto/validator_change.proto
cargo:rerun-if-changed=../types/src/proto/access_path.proto
cargo:rerun-if-changed=../types/src/proto/validator_set.proto
cargo:rerun-if-changed=../types/src/proto/ledger_info.proto
cargo:rerun-if-changed=../types/src/proto/transaction_info.proto
cargo:rerun-if-changed=src/proto/shared/mempool_status.proto
cargo:rerun-if-changed=src/proto/mempool.proto

--- stderr
mempool.proto: No such file or directory
thread 'main' panicked at 'failed to write descriptor set: Custom { kind: Other, error: StringError("protoc (\"protoc\" \"-I../types/src/proto\" \"-Isrc/proto/shared\" \"-Isrc/proto\" \"--descriptor_set_out=/var/folders/_l/kl9pdj2x50v7416j8htb6w740000gn/T/92b1f05b721041fc95462b7c76b89760\" \"--include_imports\" \"mempool.proto\") exited with non-zero exit code") }', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
```

**Comment by 4ntoine** [comment] 2019-07-05 19:43
However i was able to compile with changes from https://github.com/vjoke/libra.git

**Comment by ShubhamTatvamasi** [comment] 2019-07-12 19:19
For macOS installation libra's dependencies will be installed by the latest version of Homebrew, please run the following command to fix this issue:
```bash
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```

Source: https://brew.sh

**Comment by viczhang** [comment] 2019-08-05 04:11
"brew upgrade protobuf" fixed my problem too.

**Comment by will1989** [comment] 2019-11-12 09:28
Build failed on Ubuntu
./scripts/cli/start_cli_testnet.sh
Building and running client in debug mode.
   Compiling grpcio-sys v0.5.0-alpha.4
   Compiling prost v0.5.0
   Compiling num_enum v0.4.1
error: failed to run custom build command for `grpcio-sys v0.5.0-alpha.4`

Caused by:
  process didn't exit successfully: `/home/wuzhanfeng/projects/local-dev/libra/target/debug/build/grpcio-sys-6961b9ae4ae7b5be/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=grpc_wrap.cc
cargo:rerun-if-changed=grpc
cargo:rerun-if-env-changed=UPDATE_BIND
cargo:rerun-if-env-changed=CARGO_CFG_TARGET_OS
cargo:rerun-if-env-changed=GRPCIO_SYS_USE_PKG_CONFIG
cargo:rerun-if-env-changed=CARGO_CFG_TARGET_OS
running: "cmake" "/home/wuzhanfeng/.cargo/registry/src/github.com-1ecc6299db9ec823/grpcio-sys-0.5.0-alpha.4/grpc" "-DGO_EXECUTABLE=fake-go-nonexist" "-DgRPC_INSTALL=false" "-DgRPC_BUILD_CSHARP_EXT=false" "-DgRPC_BUILD_CODEGEN=false" "-DgRPC_BENCHMARK_PROVIDER=none" "-DCMAKE_INSTALL_PREFIX=/home/wuzhanfeng/projects/local-dev/libra/target/debug/build/grpcio-sys-ddefbb8e3a45be9f/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=c++" "-DCMAKE_BUILD_TYPE=Debug"
-- The CXX compiler identification is unknown
-- Configuring incomplete, errors occurred!
See also "/home/wuzhanfeng/projects/local-dev/libra/target/debug/build/grpcio-sys-ddefbb8e3a45be9f/out/build/CMakeFiles/CMakeOutput.log".
See also "/home/wuzhanfeng/projects/local-dev/libra/target/debug/build/grpcio-sys-ddefbb8e3a45be9f/out/build/CMakeFiles/CMakeError.log".

--- stderr
CMake Error at CMakeLists.txt:31 (project):
  The CMAKE_CXX_COMPILER:

    c++

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


thread 'main' panicked at '
command did not execute successfully, got: exit code: 1

build script failed, must exit now', /home/wuzhanfeng/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.42/src/lib.rs:861:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by bmwill** [comment] 2020-01-21 19:49
The external dependencies needed to build Libra have been simplified and should only require Rust now so this shouldn't be an issue anymore on master. If it is, please let us know.

**Closed by bmwill** 2020-01-21 19:49 UTC
Labels: bug
