### ISSUE TITLE
[Bug] get_balance returns 0 including for addresses with funds

### ISSUE THREAD

**Issue by gbenattar** [libra/libra#1341] opened 2019-10-16 09:21 UTC
# 🐛 Bug

Runtime issue returning a balance (from get_balance of Libra client) equal to 0 including for addresses with fund (source of truth used is https://libexplorer.com/address/91ab715b12554e87d998c17a3962321d23125461a3cd2ac7495c06792481ddcc after address minted using the POST REST endpoint "faucet.testnet.libra.org".

## To reproduce

**Code snippet to reproduce**
* Revision hash: 8b7b9ae47cc92da22113fd98d66826b924c0e239
* Branch: testnet
* Related issue: https://community.libra.org/t/mint-doesnt-work-under-linux-ubuntu/1901
* Rust: rustc 1.40.0-nightly (787005079 2019-10-04)
* Perform get_balance for 91ab715b12554e87d998c17a3962321d23125461a3cd2ac7495c06792481ddcc

**Comment by oleiba** [comment] 2019-10-16 09:30
Another way to reproduce:
```
libra% account create 
>> Creating/retrieving next account from wallet
Created/retrieved account #0 address 1bfb3b36384dabd29e38b4a0eafd9797b75141bb007cea7943f8a4714d3d784a
libra% account mint 0 150
>> Minting coins
Mint request submitted
libra% query balance 0
Balance is: 0.000000
```

**Comment by kphfb** [comment] 2019-10-17 04:14
We found an issue and pushed a new release which fixes the issue.  Please confirm and close this issue if it now works for you, thanks!

**Comment by kphfb** [comment] 2019-10-17 04:18
Tested it and it works on my side.  Please re-open if it isn't working for you

**Closed by kphfb** 2019-10-17 04:18 UTC
Labels: bug

**Comment by gbenattar** [comment] 2019-10-17 04:35
I am reopening the issue:
1. It does not reference the fix, did you referenced this issue in the pull request? Can you please add the link here?
2. About testing, how can such regression be prevented? 
2.1 Do you have CI/CD on this repository (at least running basic tests automatically)?
2.2 If tests are missing to cover such issue can we open a new issue to add them?\

Thanks,

**Comment by gbenattar** [comment] 2019-10-17 11:11
In addition what is the motivation for the `testnet` branch? What is your gitflow?

**Comment by runtian-zhou** [comment] 2019-10-17 20:44
The bug was due to an overflow in the TotalMarketCap resource. Namely people minted too much libra and the total market cap reaches u64::max and would prevent us from further minting due to the mint logic. See the code [here](https://github.com/libra/libra/blob/1c6f73e0eafe6cc74f0736e45bad5115f7718718/language/stdlib/modules/libra_coin.mvir#L41).  

This should be a testnet only issue and only thing we can do now is to restart the testnet. In the real world scenario we really can't mint that much of libra.

**Comment by runtian-zhou** [comment] 2019-10-17 21:27
> In addition what is the motivation for the `testnet` branch? What is your gitflow?

The motivation is that this will be the checkpoint of the version of running testnet software. This also means that in order to communicate with testnet, you need to build your local client on that branch, as there can be some breaking change on the master that might cause backward compatibility issue.
