### ISSUE TITLE
[Feature Request]Support dynamic call module at runtime.

### ISSUE THREAD

**Issue by jolestar** [libra/libra#1567] opened 2019-10-30 07:17 UTC
# 🚀 Feature Request

## Motivation

I try to implement some ethereum solidity Defi protocol on Move, find Move miss the feature of dynamic call module at runtime.  Call another module in Move must determinate at the compile time. 

Developers can not call a module by the module address, function name, and args. So Module developer can not provide a dynamic Module registration mechanism that implements the Module base an Interface, and let another developer implements the interface then register at runtime.

**Is your feature request related to a problem? Please describe.**

## Pitch

**Describe the solution you'd like**

provider a buildin method call(ModuleAddress, ModuleName, functionName, args).

**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
Yes

**Comment by tnowacki** [comment] 2019-10-31 20:45
Thanks for the request! Unfortunately, we have no plans on adding dynamic dispatch, and made a conscious and active decision to not have it. In other words, it is unlikely we will ever add dynamic dispatch. Our module system is designed intentionally to make code more explicit, and to force the programmer into a more straightforward style of static delegation. 

That being said, there may be other features needed to solve your problem, or your problem might be solvable in a different way that is already expressible in Move. 
Do you have a small example of the use case you are trying to support? This will make it a lot easier to try to help you in the right direction.

**Comment by jolestar** [comment] 2019-11-04 04:01
Such as I implement a Market Module, support Token exchange on the chain. But  I can not know which Token will support in the future. So I define an interface protocol(contains transfer method, etc), every Token that wants exchange in the marked must implement the interface protocol.

And then, I provider a Token register, the Token developer should register their Token, tell the Market Module the Token's Module address. 

When a trade user wants to exchange tow Token,  the Market Module can do an exchange by dynamic call Token's transfer method.

How I can provide such a mechanism in Move?

**Comment by tnowacki** [comment] 2019-11-04 21:43
It's hard to suggest a solution without seeing some example code. Do you have a short example that you could write (assuming the language had dynamic dispatch of some sort)?

**Comment by jolestar** [comment] 2019-11-12 05:26
I try to implement a sample Module Market, it allows the user to deposit one Token, and borrow another Token. 

```
//! account: tokena
//! account: tokenb
//! account: market_owner
//! account: usera

//! new-transaction
//! sender: market_owner
module Market {
    import 0x0.Hash;

    resource TokenRegister{
        register: Map<bytearray, TokenInfo>,
    }

    resource TokenInfo {
        token_id: bytearray,
        module_address: address,
        module_name: string,
        token_name: string,
    }

    resource TokenPool<T:resource> {
        token_id: bytearray,
        token: T,
        total_balance: u64,
    }

    resource DepositRecord {
        //assuming Move has support map, keep a token id to amount map for a user.
        records: Map<bytearray, u64>
    }

    resource BorrowRecord {
        //assuming Move has support map, keep a token id to amount map for a user.
        records: Map<bytearray, u64>
    }

    resource TokenPrice {
        // token id to price. update by oracle.
        records: Map<bytearray, u64>
    }

    get_token_info(token_id: bytearray): &TokenInfo{
        // get token info from register.
    }

    save_token_info(token_info){
        // save token info to TokenRegister,
    }

    // only market owner can call this method.
    public register_token<T:resource>(module_address: address, module_name: string, token_name: string, zero_token: T){
        let token_info: Self.TokenInfo;
        let token_pool: Self.TokenPool<T>;
        let token_id: bytearray,

        assert(get_txn_sender() == {{market_owner}}, 1024);

        //assuming exist a hash function like this.
        token_id = Hash.hash(copy(module_address), copy(module_name), copy(token_name));
        token_info = TokenInfo{
            token_id: copy(token_id),
            module_address: move(module_address),
            module_name: move(module_name),
            token_name: move(token_name),
        }

        token_pool = TokenPool<T>{
            token_id: copy(token_id),
            token: move(zero_token),
            total_balance: 0,
        };
        Self.save_token_info(move(token_info));
        move_to_sender<TokenPool<T>>(token_pool);
        return move(token_id_ref);
    }

    public deposit<T:resource>(token: T){
        let token_pool: &mut Self.TokenPool<T>;
        let token_id: bytearray,
        let token_info: & Self.TokenInfo;
        let token_ref: &mut T;
        let amount: u64;

        token_pool = borrow_global_mut<TokenPool<T>>(hard_code_owner_address);
        token_id = *&copy(token_pool).token_id;
        token_info = Self.get_token_info(copy(token_id));
        token_ref = &mut copy(token_pool).token;

        //assuming exist a call module function.
        //merge the token to token pools.
        amount = call(*&copy(token_info).module_address, *&copy(token_info).module_name, "deposit", move(token_ref), move(token));
        *(&mut copy(token_pool).total_balance) = *(&copy(token_pool).total_balance) + copy(amount);
        Self.update_deposit_record(copy(token_id),copy(amount));
    }

    update_deposit_record(token_id: bytearray, amount: u64){
        let deposit_record: &mut Self.DepositRecord;
        // borrow from sender, and update record map.
    }

    public borrow<T:resource>(amount: u64): T{
       let token_pool: &mut Self.TokenPool<T>;
       let token_id: bytearray,
       let token_info: & Self.TokenInfo;
       let token_ref: &mut T;
       let borrow_token: T;

       token_pool = borrow_global_mut<TokenPool<T>>({{market_owner}});
       token_id = *&copy(token_pool).token_id;
       token_info = Self.get_token_info(copy(token_id));
       token_ref = &mut copy(token_pool).token;

       assert(amount <= calculate_borrow_amount(amount), 1025);

       borrow_token = call(*&copy(token_info).module_address, *&copy(token_info).module_name, "withdraw", move(token_ref), move(token));
       *(&mut copy(token_pool).total_balance) = *(&copy(token_pool).total_balance) - copy(amount);
       Self.update_borrow_record(copy(token_id), amount);
       return move(borrow_token);
    }

    calculate_rate(token_id: bytearray): u64{
        //calculate rate by token price and pool balance.
    }

    calculate_borrow_amount(token_id: bytearray): u64{
        //calculate sender borrow amount for a token with deposit_record and borrow_record.
    }

    update_borrow_record(token_id: bytearray, amount: u64){
        let borrow_record: &mut Self.BorrowRecord;
       // borrow from sender, and update borrow record map.
    }

    public withdraw<T:resource>(amount: u64):T {
        // sender withdraw token
        // check borrow_record
        // check deposit_record
        // withdraw from token pool
        // update deposit record.
    }

    public repay<T:resource>(token: T) {
        // sender repay token.
        // check borrow_record
        // check deposit_record
        // check calculate_rate
        // deposit to token pool
        // update borrow record.
    }

    // init sender's market
    public init(){
        move_to_sender(empty_borrow_record);
        move_to_sender(empty_deposit_record);
    }

}


//! new-transaction
//! sender: tokena
module TokenA {

     resource T {
        value: u64,
     }

     public withdraw_from_sender(amount: u64): Self.T {
       //  withdraw T from txn sender.
       // omit the implements
     }

     public deposit_to(payee: address, token: Self.T) {
       // deposit token to payee
       // omit the implements
       return;
     }

     public balance_of(token_ref: &Self.T): u64{
        return *&move(token_ref).value;
     }

     public zero_token(): Self.T {
        return T{ value: 0};
     }

    public deposit(token_ref: &mut Self.T, check: Self.T): u64 {
        let value: u64;
        let check_value: u64;

        value = *(&mut copy(token_ref).value);
        T { value: check_value } = move(check);
        *(&mut move(token_ref).value)= move(value) + copy(check_value);
        return move(check_value);
    }

    public withdraw(token_ref: &mut Self.T, amount: u64): Self.T {
        let value: u64;

        // Check that `amount` is less than the coin's value
        value = *(&mut copy(token_ref).value);
        assert(copy(value) >= copy(amount), 10);

            // Split the coin
        *(&mut move(token_ref).value) = move(value) - copy(amount);
        return T{value: move(amount)};
    }
}

//! new-transaction
//! sender: tokenb
module TokenB {
    // omit the implements, same as TokenA.
}

//! new-transaction
//! sender: market_owner

import {{tokenb}}.TokenA;
import {{market_owner}}.Market;
main(){
   Market.register_token<TokenA.T>({{tokena}}, "TokenA", token_name: "TA", TokenA.zero_token());
   return;
}

//! new-transaction
//! sender: market_owner

import {{tokenb}}.TokenB;
import {{market_owner}}.Market;
main(){
   Market.register_token<TokenB.T>({{tokenb}}, "TokenB", token_name: "TB", TokenB.zero_token());
   return;
}

//! new-transaction
//! sender: usera

import {{tokena}}.TokenA;
import {{market_owner}}.Market;
main(){
    let token: TokenA.T;
    //assuming usera has TokenA.
    token = TokenA.withdraw_from_sender(10000);
    Market.deposit<TokenA.T>(move(token));
    return;
}

//! new-transaction
//! sender: userb

import {{tokenb}}.TokenB;
import {{market_owner}}.Market;
main(){
    let token: TokenB.T;
    //assuming userb has TokenB.
    token = TokenB.withdraw_from_sender(10000);
    Market.deposit<TokenB.T>(move(token));
    return;
}

//! new-transaction
//! sender: usera

import {{tokenb}}.TokenB;
import {{market_owner}}.Market;
main(){
    let token: TokenB.T;
    //usera borrow TokenB
    token = Market.borrow<TokenB.T>(1000);
    TokenB.deposit_to(get_txn_sender(), move(token));
    return;
}

```

**Comment by jolestar** [comment] 2019-11-12 06:17
I think if Move does not support dynamic dispatch, it should support something like Trait in rust, and can binding Trait to a resource, then we can use Generic to solve this problem.

**Comment by tnowacki** [comment] 2019-11-13 19:35
While we will not be adding dynamic dispatch (nor any form of traits or interfaces), there are some approaches you can take to implement programs like this.

Keep in mind in Move, intent needs to be much more clear (this is by design), so writing overly general code that works with absolutely anything that has `deposit`/`withdraw`/`value` isn't going to work.

That being said, the first thing needed for this is a generalized `Token` module. The market can  only work over coins declared by that module. But! This module can be used to declare any number of tokens.

Here is the example Token module. You could imagine something like this becoming almost a sort of ERC-20 like standard.

```rust
address 0x1:

module Token {
    use 0x0.Transaction;

    resource struct Coin<AssetType: copyable> {
        type: AssetType,
        value: u64,
    }

    // control the minting/creation in the defining module of `ATy`
    public create<ATy: copyable>(type: ATy, value: u64): Coin<ATy> {
        Coin { type, value: 0 }
    }

    public value<ATy: copyable>(coin: &Coin<ATy>): u64 {
        coin.value
    }

    public split<ATy: copyable>(coin: Coin<ATy>, amount: u64): (Coin<ATy>, Coin<ATy>) {
        let other = withdraw(&mut coin, amount);
        (coin, other)
    }

    public withdraw<ATy: copyable>(coin: &mut Coin<ATy>, amount: u64): Coin<ATy> {
        Transaction.assert(coin.value >= amount, 10);
        coin.value = coin.value - amount;
        Coin { type: *&coin.type, value: amount }
    }

    public join<ATy: copyable>(coin1: Coin<ATy>, coin2: Coin<ATy>): Coin<ATy> {
        deposit(&mut coin1, coin2);
        coin1
    }

    public deposit<ATy: copyable>(coin: &mut Coin<ATy>, check: Coin<ATy>) {
        let Coin { value, type } = check;
        Transaction.assert(&coin.type == &type, 42);
        coin.value = coin.value + value;
    }

    public destroy_zero<ATy: copyable>(coin: Coin<ATy>) {
        let Coin { value, type: _ } = coin;
        Transaction.assert(value == 0, 11)
    }

}
```

Since the `AssetType` would be a struct controlled by another module, that other module can control minting and--to some degree--destruction.

For example:

```rust
address 0x70DD:

module ToddNickles {
    use 0x1.Token;
    use 0x0.Transaction;

    struct T {}

    resource struct Wallet {
        nickles: Token.Coin<T>,
    }

    public init() {
        Transaction.assert(Transaction.sender() == 0x70DD, 42);
        move_to_sender(Wallet { nickles: Token.create(T{}, 0) })
    }

    public mint(): Token.Coin<T> {
        Transaction.assert(Transaction.sender() == 0x70DD, 42);
        Token.create(T{}, 5)
    }

    public destroy(c: Token.Coin<T>) acquires Wallet {
        Token.deposit(&mut borrow_global_mut<Wallet>(0x70DD).nickles, c)
    }

}
```

(Note: You can think of `Token.Coin` *almost* as an interface. But `ToddNickles` can only implement one interface. If you want it to implement another, e.g. `Token2.Coin` you would have to write a translation/exchange layer between the two "interfaces")

With that in mind, a market could be implemented over this token.
Note: the module extensively uses generic instantiations of resources which is not currently supported with global storage, we plan on adding that feature (i.e. `move_to_sender<MyResource<T>>(...)` is not supported)

```rust
address 0xB055:

module OneToOneMarket {
    use 0x0.Transaction;
    use 0x1.Token;

    resource struct Pool<AssetType: copyable> {
        coin: Token.Coin<AssetType>,
    }

    resource struct DepositRecord<InputAsset: copyable, OutputAsset: copyable> {
        record: u64,
    }

    resource struct BorrowRecord<InputAsset: copyable, OutputAsset: copyable> {
        record: u64,
    }

    resource struct Price<InputAsset: copyable, OutputAsset: copyable> {
        price: u64,
    }

    accept<AssetType: copyable>(init: Token.Coin<AssetType>) {
        let sender = Transaction.sender();
        if (!exists<Pool<AssetType>>(sender)) move_to_sender(Pool<AssetType> { coin: init })
    }

    public register_price<In: copyable, Out: copyable>(
        initial_in: Token.Coin<In>,
        initial_out: Token.Coin<Out>,
        price: u64
    ) {
        Transaction.assert(Transaction.sender() == 0xB055, 42); // assert sender is module writer
        accept<In>(initial_in);
        accept<Out>(initial_out);
        move_to_sender(Price<In, Out> { price })
    }

    public deposit<In: copyable, Out: copyable>(coin: Token.Coin<In>)
        acquires Pool<In>, DepositRecord<In, Out>
    {
        let amount = Token.value(&coin);

        update_deposit_record<In, Out>(amount);

        let pool = borrow_global_mut<Pool<In>>(0xB055);
        Token.deposit(&mut pool.coin, coin)
    }

    public borrow<In: copyable, Out: copyable>(
        amount: u64,
    ): Token.Coin<Out>
        acquires Price<In, Out>, Pool<Out>, DepositRecord<In, Out>, BorrowRecord<In, Out>
    {
        Transaction.assert(amount <= max_borrow_amount<In, Out>(), 1025);

        update_borrow_record<In, Out>(amount);

        let pool = borrow_global_mut<Pool<Out>>(0xB055);
        Token.withdraw(&mut pool.coin, amount)
    }

    max_borrow_amount<In: copyable, Out: copyable>(): u64
        acquires Price<In, Out>, Pool<Out>, DepositRecord<In, Out>, BorrowRecord<In, Out>
    {
        let sender = Transaction.sender();

        let input_deposited = deposited_amount<In, Out>();
        let output_deposited = borrowed_amount<In, Out>();

        let input_into_output =
            input_deposited * borrow_global<Price<In, Out>>(0xB055).price;
        let max_output =
            if (input_into_output < output_deposited) 0
            else (input_into_output - output_deposited);
        let available_output = {
            let pool = borrow_global<Pool<Out>>(0xB055);
            Token.value(&pool.coin)
        };
        if (max_output < available_output) max_output else available_output

    }

    update_deposit_record<In: copyable, Out: copyable>(amount: u64)
        acquires DepositRecord<In, Out>
    {
        let sender = Transaction.sender();
        if (!exists<DepositRecord<In, Out>>(sender)) {
            move_to_sender(DepositRecord<In, Out> { record: 0 })
        };
        let record = &mut borrow_global_mut<DepositRecord<In, Out>>(sender).record;
        *amount = *record + amount
    }

    update_borrow_record<In: copyable, Out: copyable>(amount: u64)
        acquires BorrowRecord<In, Out>
    {
        let sender = Transaction.sender();
        if (!exists<BorrowRecord<In, Out>>(sender)) {
            move_to_sender(BorrowRecord<In, Out> { record: 0 })
        };
        let record = &mut borrow_global_mut<BorrowRecord<In, Out>>(sender).record;
        *amount = *record + amount
    }

    deposited_amount<In: copyable, Out: copyable>(): u64
        acquires DepositRecord<In, Out>
    {
        let sender = Transaction.sender();
        if (!exists<DepositRecord<In, Out>>(sender)) return 0;
        borrow_global<DepositRecord<In, Out>>(sender).record
    }

    borrowed_amount<In: copyable, Out: copyable>(): u64
        acquires BorrowRecord<In, Out>
    {
        let sender = Transaction.sender();
        if (!exists<BorrowRecord<In, Out>>(sender)) return 0;
        borrow_global<BorrowRecord<In, Out>>(sender).record
    }

    // ... other functions ...

}
```

And for your own edification, I noticed that in your original market example (and in my recreation here) you tended to use the address of the module to create a sort of quasi-singleton instance of this market. That is not strictly necessary in Move! You can program in a more generalized way that allows anyone to instantiate resources in the module (i.e. you can let someone else use the same module to create their own market).

For example

```rust
address 0x0:

module Map {
    native struct T<K, V>;

    native public empty<K, V>(): T<K, V>;

    native public get<K, V>(m: &T<K, V>, k: &K): &V;
    native public get_mut<K, V>(m: &mut T<K, V>, k: &K): &mut V;

    native public contains_key<K, V>(m: &T<K, V>, k: &K): bool;
    // throws on duplicate as I don't feel like mocking up Option
    native public insert<K, V>(m: &T<K, V>, k: K, v: V);
    // throws on miss as I don't feel like mocking up Option
    native public remove<K, V>(m: &T<K, V>, k: &K): V;
}

address 0x2:

module OneToOneMarket {
    use 0x0.Transaction;
    use 0x0.Map;
    use 0x1.Token;

    resource struct Pool<AssetType: copyable> {
        coin: Token.Coin<AssetType>,
    }

    resource struct DepositRecord<InputAsset: copyable, OutputAsset: copyable> {
        // pool owner => amount
        record: Map.T<address, u64>
    }

    resource struct BorrowRecord<InputAsset: copyable, OutputAsset: copyable> {
        // pool owner => amount
        record: Map.T<address, u64>
    }

    resource struct Price<InputAsset: copyable, OutputAsset: copyable> {
        price: u64,
    }

    accept<AssetType: copyable>(init: Token.Coin<AssetType>) {
        let sender = Transaction.sender();
        if (!exists<Pool<AssetType>>(sender)) move_to_sender(Pool<AssetType> { coin: init })
    }

    public register_price<In: copyable, Out: copyable>(
        initial_in: Token.Coin<In>,
        initial_out: Token.Coin<Out>,
        price: u64
    ) {
        accept<In>(initial_in);
        accept<Out>(initial_out);
        move_to_sender(Price<In, Out> { price })
    }

    public deposit<In: copyable, Out: copyable>(pool_owner: address, coin: Token.Coin<In>)
        acquires Pool<In>, DepositRecord<In, Out>
    {
        let amount = Token.value(&coin);

        update_deposit_record<In, Out>(pool_owner, amount);

        let pool = borrow_global_mut<Pool<In>>(pool_owner);
        Token.deposit(&mut pool.coin, coin)
    }

    public borrow<In: copyable, Out: copyable>(
        pool_owner: address,
        amount: u64,
    ): Token.Coin<Out>
        acquires Price<In, Out>, Pool<Out>, DepositRecord<In, Out>, BorrowRecord<In, Out>
    {
        Transaction.assert(amount <= max_borrow_amount<In, Out>(pool_owner), 1025);

        update_borrow_record<In, Out>(pool_owner, amount);

        let pool = borrow_global_mut<Pool<Out>>(pool_owner);
        Token.withdraw(&mut pool.coin, amount)
    }

    max_borrow_amount<In: copyable, Out: copyable>(pool_owner: address): u64
        acquires Price<In, Out>, Pool<Out>, DepositRecord<In, Out>, BorrowRecord<In, Out>
    {
        let sender = Transaction.sender();

        let input_deposited = deposited_amount<In, Out>(pool_owner);
        let output_deposited = borrowed_amount<In, Out>(pool_owner);

        let input_into_output =
            input_deposited * borrow_global<Price<In, Out>>(pool_owner).price;
        let max_output =
            if (input_into_output < output_deposited) 0
            else (input_into_output - output_deposited);
        let available_output = {
            let pool = borrow_global<Pool<Out>>(pool_owner);
            Token.value(&pool.coin)
        };
        if (max_output < available_output) max_output else available_output

    }

    update_deposit_record<In: copyable, Out: copyable>(pool_owner: address, amount: u64)
        acquires DepositRecord<In, Out>
    {
        let sender = Transaction.sender();
        if (!exists<DepositRecord<In, Out>>(sender)) {
            move_to_sender(DepositRecord<In, Out> { record: Map.empty() })
        };
        let record = &mut borrow_global_mut<DepositRecord<In, Out>>(sender).record;
        if (Map.contains_key(record, &pool_owner)) {
            let old_amount = Map.remove(record, &pool_owner);
            amount = amount + old_amount;
        };
        Map.insert(record, pool_owner, amount)
    }

    update_borrow_record<In: copyable, Out: copyable>(pool_owner: address, amount: u64)
        acquires BorrowRecord<In, Out>
    {
        let sender = Transaction.sender();
        if (!exists<BorrowRecord<In, Out>>(sender)) {
            move_to_sender(BorrowRecord<In, Out> { record: Map.empty() })
        };
        let record = &mut borrow_global_mut<BorrowRecord<In, Out>>(sender).record;
        if (Map.contains_key(record, &pool_owner)) {
            let old_amount = Map.remove(record, &pool_owner);
            amount = amount + old_amount;
        };
        Map.insert(record, pool_owner, amount)
    }

    deposited_amount<In: copyable, Out: copyable>(pool_owner: address): u64
        acquires DepositRecord<In, Out>
    {
        let sender = Transaction.sender();
        if (!exists<DepositRecord<In, Out>>(sender)) return 0;

        let record = &borrow_global<DepositRecord<In, Out>>(sender).record;
        if (Map.contains_key(record, &pool_owner)) *Map.get(record, &pool_owner)
        else 0
    }

    borrowed_amount<In: copyable, Out: copyable>(pool_owner: address): u64
        acquires BorrowRecord<In, Out>
    {
        let sender = Transaction.sender();
        if (!exists<BorrowRecord<In, Out>>(sender)) return 0;

        let record = &borrow_global<BorrowRecord<In, Out>>(sender).record;
        if (Map.contains_key(record, &pool_owner)) *Map.get(record, &pool_owner)
        else 0
    }
}
```

Hopefully this gives you some ideas of how to program in the absence of dynamic dispatch.

As I mentioned before, Move is designed to be much more intentional. It is not designed to be as flexible as a general purpose programming language. In something like Rust or Java, you respectively use traits and interfaces as a way of compartmentalizing code to say: My code only cares that the methods exist on this piece of data. It does not care how the data implements the trait or interface, it just cares that its there.

We don't think this sort of opaque abstraction something you want present in a blockchain.

When code is law, interfaces are a crime.

The interface or trait declares no intent for the code, only that functionality exists. When programming with assets, it is our belief that intent of how assets are manipulated needs to be transparent.

**Comment by jolestar** [comment] 2019-11-14 03:21
Thanks, @tnowacki, I got it. But I try it that move_to_sender<MyResource<T>>(...) has supported in MoveIR funcional_test,  What it means "which is not currently supported with global storage"?

**Comment by tnowacki** [comment] 2019-11-14 19:47
`move_to_sender<MyResource<T>>(...) ` is not supported

**Comment by jolestar** [comment] 2019-11-15 02:15
I tried the following code，it is work for functional_test.

'''
module G{
    resource R<T:resource> {
        t: T,
    }

    public new<T:resource>(t: T): Self.R<T>{
        return R<T>{ t: move(t)};
    }

    public save<T:resource>(r: Self.R<T>) {
        move_to_sender<R<T>>(move(r));
        return;
    }
}

//! new-transaction

module Token{

    resource T{
        value: u64,
    }

    public new(value: u64): Self.T {
        return T{value: move(value)};
    }
}

//! new-transaction
import {{default}}.G;
import {{default}}.Token;

main(){
   let token: Token.T;
   let r: G.R<Token.T>;

   r = G.new<Token.T>(Token.new(100));
   G.save<Token.T>(move(r));
   return;
}
'''

**Comment by tnowacki** [comment] 2019-11-15 19:19
That's a bug. We will get a patch up later today

**Comment by jolestar** [comment] 2019-11-18 02:44
I hope to support this feature quickly.

**Comment by tnowacki** [comment] 2019-11-18 21:07
Heres the bug fix to correctly block this feature: 
https://github.com/libra/libra/pull/1772

Unfortunately, I don't have a timeline of when it will be added. 

I'm going to go ahead and close this issue around dynamic dispatch, feel free to reach out with any other questions.

**Closed by tnowacki** 2019-11-18 21:07 UTC
Labels: enhancement, language, wontfix
