### ISSUE TITLE
[Bug] Need to randomize which VFNs public fullnodes connect to

### ISSUE THREAD

**Issue by coryhill** [libra/libra#5437] opened 2020-08-03 17:17 UTC
# 🐛 Bug

My public fullnode has been running on premainnet since Saturday but has not been able to sync yet because it is unable to reach any of the 3 peers it's trying to connect to. This set of 3 peers has persisted across restarts and a data wipe. 

## To reproduce

Try to start up a public fullnode on premainnet

**Stack trace/error message**
```
ERROR 2020-08-03 17:12:40 network/src/peer_manager/mod.rs:945 [Public,full_node,704c368e] Error dialing Peer 027bcd02 at /dns4/a618747270806470489784d397d672f5-a4ce02b3daf7fc56.elb.us-west-2.amazonaws.com/tcp/6182/ln-noise-ik/c890408bf3ad1bc13a7dd80d31d0d58c9a7372a32639a5f390e41653ef905b66/ln-handshake/0
ERROR 2020-08-03 17:13:25 network/src/peer_manager/mod.rs:945 [Public,full_node,704c368e] Error dialing Peer 1bb11a02 at /ip4/52.190.44.228/tcp/6182/ln-noise-ik/1e4a0c2439331956b0473fc56d257739ba62977bfdeb908d391b5ac75e706756/ln-handshake/0
ERROR 2020-08-03 17:13:25 network/src/peer_manager/mod.rs:945 [Public,full_node,704c368e] Error dialing Peer 30ca4f96 at /ip4/34.69.223.136/tcp/6182/ln-noise-ik/3b9ba1f7f5b5b1fe0c7c0f3824bf60dc0ab5093835d8a31bc8a62af2fc0a6107/ln-handshake/0
```

## Expected Behavior

The three peers should be chosen at random at service start, and ideally a new set of random peers should be chosen at regular intervals.

## System information

**Please complete the following information:**
- Libra 0.18

**Comment by gregnazario** [comment] 2020-08-03 17:21
Possible related code for dialing peers.  However, it should only use this code on a "non-public" network.
https://github.com/libra/libra/blob/master/network/src/connectivity_manager/mod.rs#L355-L379

Need to look at the upstream peer setup to tell where the Public network fallback is connecting like that.

Were there any other network logs?

**Comment by gregnazario** [comment] 2020-08-03 17:23
In addition, if your node has never connected to the chain, it uses the seed peers that it was configured with to try to connect to.

**Comment by gregnazario** [comment] 2020-08-03 17:31
I think it may be trying to connect to outdated seed peers.  I tried to resolve the DNS on the first record that didn't work, and the other two wouldn't respond.  @phlip9 knows more than me about the seed peers, but if you've never connected to the network, then there's no way to ever update these peers to connect to anyways.

**Comment by mgorven** [comment] 2020-08-03 17:36
These seed peers are in the genesis blob BTW. There are 25 of them, it should at least be trying them all.

**Comment by gregnazario** [comment] 2020-08-03 17:39
Yeah, it should try them all and I can adjust it accordingly to do that.

**Comment by gregnazario** [comment] 2020-08-03 17:44
Oh hmm. We do choose randomly a group to make requests to https://github.com/libra/libra/blob/master/network/src/connectivity_manager/mod.rs#L385

We shouldn't be using connectivity manager on a full node though to a public network.

Are there any logs that say something like:
```
{} Dial future: dialing peer: {}, at address: {}, after delay: {}",
```

**Comment by gregnazario** [comment] 2020-08-03 18:23
I think there are a couple action items from this:
1. We should probably say why we failed to connect to the host (all of those are because the peers don't exist or aren't listening)
2. We should have something that tells us where the DialPeer request comes from.  These don't come from `ConnectivityManager`, because it's a public network.  But, that means it comes from a downstream network sender, and it seems to be harder to trace.
3. The most important, we are deterministically choosing which peers to Dial from an application based on the Genesis seed peers, but those peers are gone.  We should iterate through all the peers to dial.

**Comment by coryhill** [comment] 2020-08-03 19:33
When you said the peers didn't exist, it made me wonder if I was using the most recent genesis blob, which I apparently was not. I've relaunched with the current blob and now I'm seeing different behavior. It does appear to be iterating through peers, although it is still unable to connect.

```
ERROR 2020-08-03 19:27:37 network/src/peer_manager/mod.rs:966 [Public,full_node,4de76531] Error dialing Peer 2f5e8391 at /dns4/fullnode.02351ec7-f345-432d-9559-2f30a634553b.libra.bison.run/tcp/6182/ln-noise-ik/1d42129f485d346d24aa2cf5b06875273ac35234e81cc5b6cea3fcee9cba0e00/ln-handshake/0
ERROR 2020-08-03 19:28:03 network/src/peer_manager/mod.rs:966 [Public,full_node,4de76531] Error dialing Peer 33e9e5c6 at /dns4/temasek-full-node.man.bdi.sh/tcp/6182/ln-noise-ik/d38c85c574f43b239f51e894f529b1eda65762fae88dc1ee55636dd8f557fb20/ln-handshake/0
ERROR 2020-08-03 19:28:13 network/src/peer_manager/mod.rs:966 [Public,full_node,4de76531] Error dialing Peer 612fdabd at /dns4/af94dba999ebb4e6f93e9c26c2858c25-83ad3472e0f56803.elb.eu-west-1.amazonaws.com/tcp/6182/ln-noise-ik/2d549285b7fb5d5eca96d1ca6e1adee9b38c6cb12eb35aad95bdbf6798d7a627/ln-handshake/0
ERROR 2020-08-03 19:29:08 network/src/peer_manager/mod.rs:966 [Public,full_node,4de76531] Error dialing Peer 33e9e5c6 at /dns4/temasek-full-node.man.bdi.sh/tcp/6182/ln-noise-ik/d38c85c574f43b239f51e894f529b1eda65762fae88dc1ee55636dd8f557fb20/ln-handshake/0
ERROR 2020-08-03 19:29:17 network/src/peer_manager/mod.rs:966 [Public,full_node,4de76531] Error dialing Peer 398593fa at /ip4/34.68.134.0/tcp/6182/ln-noise-ik/3356711a8ec0866b1d205dcdd4f407b1634d278ecf4c5156e2e6025f0a98c944/ln-handshake/0
ERROR 2020-08-03 19:29:47 network/src/peer_manager/mod.rs:966 [Public,full_node,4de76531] Error dialing Peer 6a91048f at /dns4/ae8db6d9b69f649fdade4f9a8eb483f4-1d143c1a31fffad4.elb.us-east-1.amazonaws.com/tcp/6182/ln-noise-ik/9c06d1f4eb365ae51af41b7ea487378095ce074d585bbbf5a20b17954b10536a/ln-handshake/0
ERROR 2020-08-03 19:30:12 network/src/peer_manager/mod.rs:966 [Public,full_node,4de76531] Error dialing Peer ab553334 at /dns4/breakthrough-full-node.man.bdi.sh/tcp/6182/ln-noise-ik/3e286c558c0875cf4922408894944cc50f5c97416ba6cae97f3efd079e808d2d/ln-handshake/0
ERROR 2020-08-03 19:30:22 network/src/peer_manager/mod.rs:966 [Public,full_node,4de76531] Error dialing Peer 681dc4ca at /dns4/a0eb8180dc5b74266afe27cb88dc2066-5aee6df4b11933f8.elb.us-west-2.amazonaws.com/tcp/6182/ln-noise-ik/82cfaf965c3ac1acc8ecf1767e0cf266550c907d0b7995fde3224ca490c24a10/ln-handshake/0
ERROR 2020-08-03 19:30:52 network/src/peer_manager/mod.rs:966 [Public,full_node,4de76531] Error dialing Peer 03bfddc8 at /dns4/a049842b8cae349708e857be33c5c064-ea2033d7c4e6936a.elb.eu-west-1.amazonaws.com/tcp/6182/ln-noise-ik/d487971852bf895b697249d59f472d3190f16587a99228f5edfa77f95dcaa235/ln-handshake/0
ERROR 2020-08-03 19:31:18 network/src/peer_manager/mod.rs:966 [Public,full_node,4de76531] Error dialing Peer 33e9e5c6 at /dns4/temasek-full-node.man.bdi.sh/tcp/6182/ln-noise-ik/d38c85c574f43b239f51e894f529b1eda65762fae88dc1ee55636dd8f557fb20/ln-handshake/0
```

**Comment by gregnazario** [comment] 2020-08-03 19:38
So, these peers do exist, and you are just unable to connect to them for a different reason.  I did a quick check to see if some of them do respond

**Comment by phlip9** [comment] 2020-08-03 19:38
There should be logs from connectivity_manager of the form `"{} Failed to connect to peer: {} at address: {}; error: {}"` that will tell us what kind of error

**Comment by gregnazario** [comment] 2020-08-03 19:40
This reminds me, we should make a runbook based on the experiences we have here.

Clearly the first step now needs to be do you have the right genesis :)

**Comment by coryhill** [comment] 2020-08-03 19:44
There are no log lines that contain "Failed to connect to peer". You say these come from ConnectivityManager, but Greg was saying it wouldn't be using ConnectivityManager.

**Comment by gregnazario** [comment] 2020-08-03 19:47
I think we can improve the logging, and log the error right at the line that you're seeing a bunch of.  Sadly, we pass the error down and then only the handling application will log it

**Comment by phlip9** [comment] 2020-08-03 19:48
It looks like the "Failed to connect to peer" is at INFO log level, is the log level only >= ERROR ?

**Comment by gregnazario** [comment] 2020-08-03 19:51
If i'm not mistaken, this is the public network and shouldn't use connectivity manager?

**Comment by phlip9** [comment] 2020-08-03 19:55
public network _listeners_ don't use connectivity manager (since they only service inbound connections). public network _clients_ use connectivity manager to dial public endpoints

**Comment by gregnazario** [comment] 2020-08-03 20:03
Interesting we log the actual error at INFO level, and the info of an error at the ERROR level.  @coryhill What's your log level set to?

**Comment by coryhill** [comment] 2020-08-03 20:06
`RUST_LOG` is set to `info`. Is there anything else I need to set?

**Comment by phlip9** [comment] 2020-08-03 20:35
weird... that should definitely show the logs then... :sob:

**Comment by coryhill** [comment] 2020-08-03 21:50
> My suspicion is that it's a configuration error; probably the full node's peer id is not derived from the pubkey...

How can I verify this?

**Comment by phlip9** [comment] 2020-08-03 22:10
the peer id should be the last 16 bytes of the noise public key (for a public full node / client)

i believe the `identity` field in the network config should not be present (it will sample a fresh keypair and correctly derive the peer id on startup)

the config yaml for the public full node should look something like:

```
full_node_networks:
    - discovery_method: "onchain"
      listen_address: "/ip4/0.0.0.0/tcp/6180"
      network_id: "public"
```

we also log the full derived config on startup, which should have

`full_node_networks[0].identity: Identity::FromConfig { key, peer_id }`

although i don't know if this will print the public key... 

if none of those work, we can find the public key in this log `"{} listening on {:?}"`

**Comment by mgorven** [comment] 2020-08-03 22:22
I think this is caused by a wrong chain_id: https://github.com/libra/partners/pull/271

**Comment by gregnazario** [comment] 2020-08-03 22:29
Hmm, perhaps we should log a ChainId mismatch, we currently don't.

**Comment by coryhill** [comment] 2020-08-03 22:41
Indeed, correcting the `chain_id` fixed it. My fullnode is now online. There is exactly one line in the log file, which is the `Using node config...` line.

**Comment by gregnazario** [comment] 2020-08-03 22:51
Okay so followup action items from this event:
1. Better logging especially for bad dials https://github.com/libra/libra/pull/5453, we can work on more in the future
2. Runbook on how to start a public full node (starting with getting the right genesis)

**Comment by coryhill** [comment] 2020-08-03 22:55
So is the set of VFNs that the fullnode connects to randomized after all?

**Comment by gregnazario** [comment] 2020-08-03 22:56
Yes, it is randomized I misspoke earlier :( https://github.com/libra/libra/blob/master/network/src/connectivity_manager/mod.rs#L385

**Comment by gregnazario** [comment] 2020-08-05 18:27
Last followup item here: https://github.com/libra/libra/issues/5485

I'm closing this, as the connections made are randomized.

**Closed by gregnazario** 2020-08-05 18:27 UTC
Labels: bug

**Comment by sm86** [comment] 2021-02-20 21:47
I see a genesis blob mismatch during the sync. How to generate Genesis for a later waypoint?

**Comment by gregnazario** [comment] 2021-02-22 18:54
> I see a genesis blob mismatch during the sync. How to generate Genesis for a later waypoint?

@sm86 I think this is the wrong place for your question about this (it's an unrelated bug report).  Feel free to ask your question in a different issue with extra information using the form here: https://github.com/diem/diem/issues/new/choose

**Comment by sm86** [comment] 2021-02-23 18:01
My apologies, I posted issue #7693. Would appreciate any kind of help, thanks in advance!
