### ISSUE TITLE
[Consensus] EpochManager as a single SoT for epoch information

### ISSUE THREAD

**Issue by dmitri-perelman** [libra/libra#1671] opened 2019-11-07 22:39 UTC
## The problem.
Current architecture is as follows:
* `NetworkTask` keeps the current epoch metadata (epoch, validators) in its state: it's responsible for filtering the messages based on this epoch metadata.
* `NetworkTask` updates the epoch metadata synchronously (right away) upon receiving `EpochChange` message that passes the proof verification.
* `EpochManager` is held by `ChainedBFTSMR`: it is generating a new `EventProcessor` on demand when the SMR learns about the `EpochChange` event.

The metadata about the epoch is thus kept by both `NetworkTask` and `EpochManager`, which is suboptimal. One problem it creates is that there is a time window between  `NetworkTask` that has already migrated to the new epoch, but the SMR still keeping the  `EventProcessor` of the old epoch (until its `select` chooses to pick an `EpochChange` event from the corresponding receiver). As a result, today the messages of epoch `n+1` pass the verification of `NetworkTask` (which is already in that epoch), and can arrive to `EventProcessor` of epoch `n` (which has not been replaced yet).

## Proposal.
We can change the `EpochManager` to be the single source of truth for epoch metadata:
* `EpochManager` is accessed both by `NetworkTask` and `ChainedBftSMR` via `Arc<RwLock<EpochManager>>`.
* `EpochManager` is keeping `Arc<RwLock<EpochState>>`, which keeps both the information about the current epoch and the `EventProcessor` corresponding to that epoch.
* Epoch transitioning is now executed in a synchronous manner: `NetworkTask` is directly invoking `EpochManager::start_new_epoch()`.

I hope this architecture could be easier to reason about because there is going to be a single source of truth and a single serialization point for the epoch transitioning.

**Comment by zekun000** [comment] 2019-11-08 00:14
in general I'm not a fan of RwLock, if the goal here is to synchronize the epoch change between network task and main loop, we could send a one-shot channel and blocked until start_new_epoch finishes.

**Comment by dmitri-perelman** [comment] 2019-11-08 00:49
The goal is two-fold: 1) synchronize the epoch change, and 2) simplify the architecture via making sure that there is a single source of truth for the epoch information (i.e., `EpochManager`).
I don't think we should worry about the perf implications of a RwLock here: we're going to use the WriteLock only for reconfiguration, while all the other requests are going through a ReadLock, which cost is negligible in comparison to the other operations.

**Comment by aching** [comment] 2019-11-08 06:53
Conceptually this seems closer to the shared state model that we have talked about in the past.  As a minor detail, I would prefer to hide the RwLock inside of the EpochManager and just have Arc<EpochManager> if we are heading down this path.

**Comment by gterzian** [comment] 2020-01-17 12:18
My five-cents as someone with no experience with the codebase, but who is generally interested in these kind of setups, and took a look at the code.

> NetworkTask updates the epoch metadata synchronously (right away) upon receiving EpochChange message that passes the proof verification.

Where does that happen? It seems to me `NetworkTask` only ever reads from `epoch_info`, and it's the epoch manager that writes to it at https://github.com/libra/libra/blob/aaca7bba4141e26cbf4ca8881105042ef68bac59/consensus/src/chained_bft/epoch_manager.rs

At [`process_epoch_change`](https://github.com/libra/libra/blob/aaca7bba4141e26cbf4ca8881105042ef68bac59/consensus/src/chained_bft/network.rs#L501) I couldn't see the actual state change. Are you talking about something else than the shared `epoch_info`?

Regarding the potential solution:

1. I think the real problem is running the `NetworkTask` and the other future(conceptually `ChainedBftSMR`?) created as part of [`start_event_processing`](https://github.com/libra/libra/blob/aaca7bba4141e26cbf4ca8881105042ef68bac59/consensus/src/chained_bft/chained_bft_smr.rs#L86) separately. If they need to depend on the same state synchronously, you might have well run them as one thing(task, thread?) and keep all this state local to that thing. Is there a reason why you couldn't do the equivalent of adding `all_events` from network to the `select` of `ChainedBftSMR`, and just pass the message to network from there as a method call(like is done with `event_processor` and `epoch_manager`)?
2. Even with a lock, you could still get a variation of the problem you describe. What you describe is essentially that the "epoch change" message sent by `NetworkTask` is only handled after other messages which are handled by the "old" event processor. The same could happen if for some reason `NetworkTask` needs to wait to acquire the lock, perhaps while it is held somewhere in the other future, and messages are handled in the meantime(with a performant but unfair lock, this could even happen if the lock is release and re-acquired for each message handled, leaving the `NetworkTask` waiting). Granted, for this particular problem, since `NetworkTask` would be blocked trying to acquire the lock, it wouldn't be able to forward incoming messages for the new epoch. But another problem might come-up. A lock around the shared-state is unlikely to hold-up as a "single source of truth" in all situations, unless paired with a signalling mechanism like a condvar.
3. If "NetworkTask is directly invoking EpochManager::start_new_epoch()", how will you then get the new event-processor returned by that call to the other future? More shared-state? Or would you hide the event-processing inside the epoch-manager, and have the other future call something like `epoch_manager.process_event`(which would require acquiring a lock)?

To me, it seems the right way to handle this(and any other similar situation that might arise if you keep the current structure), it to follow "proposal 3" of https://github.com/libra/libra/issues/2152, adding to it that also the network stuff would be part of the same single "consensus event-loop", which would allow keeping all that state in one place, and guarantee synchronous operations on that state one message at a time.

**Comment by davidiw** [comment] 2020-01-20 23:38
@gterzian, thanks for your thoughts! I started looking into issue #2152 in greater depth and realized that a lot of what was described comes as symptoms of the interaction with the networking layer.

**Comment by davidiw** [comment] 2020-01-21 19:00
@gterzian, by the way, if you want to take a stab at that, I'd be happy to iterate with you on it. No one is focused on that area at the moment.

**Comment by gterzian** [comment] 2020-01-23 06:20
Thanks for the offer, it is tempting, and I'm not sure I will have any spare energy in the near future to work on this.

Sorry, for being the one with the suggestions who doesn't actually work on it afterwards!

If I can get away with a last suggestion:

I was looking at the stuff in `libra_channel`, which I think would have to change as part of https://github.com/libra/libra/issues/2152 (or at least be supplemented with another channel type).

So if you want to run a single coherent "consensus event-loop" on a thread, as opposed to a task, I would suggest switching to a set of [`crossbeam`](https://github.com/crossbeam-rs) channel, since those will give you a similar `select` macro. (that's probably quite an obvious choice).

With regards to the business logic currently implemented in `libra_channel`, I think you could make it easier on yourself by implementing that as a wrapper around a `Receiver`, where the logic would be single-threaded and run on the thread where the receiver is found. 

You could still run the accept/reject messages logic, and you'd do it as a kind of single-threaded filter wrapping the receiver side of a shared-queue(the channel), as opposed to as part of a thread-safe shared-queue in  and of itself. 


I think you could get most, if not all, of the current logic done in that way, and it would be simpler since it would avoid shared-state. One could for example literally drain the channel of all messages at each iteration of the event-loop, and then run them through (the equivalent of) a thread-local `PerKeyQueue`.

If you need to give the network provider instant feedback in the case of the queue being full, one could actually move the `PerKeyQueue` to be local to the network provider, who could use it as a local buffer and only forward it to consensus in response to a message asking for more data.

**Comment by gterzian** [comment] 2020-02-08 05:26
Resposting this from a discussion in https://github.com/libra/libra/pull/2402 so it doesn't get among the numerous commments in that PR:

I think the below is an accurate description of a current problem with the epoch/message queuing logic. It appears to me that the description at the beginning of this issues is either outdated(perhaps the lock around `EpochInfo` was added and this issue left open?), or inaccurate(it seems to me that it's the `EpochManager` that writes to `EpochInfo`, not `NetworkTask`, perhaps this was also changed since this issue was opened).

Consider the following:

1. A proposal message comes in over the network, at about the same time as we're changing the epoch.
2. `NetworkTask` reads the current epoch at https://github.com/libra/libra/blob/dae20021ab2cb806c1daf7a62c06c28ac60ea6f9/consensus/src/chained_bft/network.rs#L418
Since the epoch hasn't changed yet, it doesn't queue the message to `different_epoch_tx`.
3. `EpochManager` writes to the current epoch at https://github.com/libra/libra/blob/dae20021ab2cb806c1daf7a62c06c28ac60ea6f9/consensus/src/chained_bft/epoch_manager.rs#L214. called into from https://github.com/libra/libra/blob/dae20021ab2cb806c1daf7a62c06c28ac60ea6f9/consensus/src/chained_bft/chained_bft_smr.rs#L125
4. `EpochManager` clears the queue, removing the **currently enqueued** proposal messages at https://github.com/libra/libra/blob/dae20021ab2cb806c1daf7a62c06c28ac60ea6f9/consensus/src/chained_bft/chained_bft_smr.rs#L127
5. `NetworkTask` queues the proposal msg that came in at 1, yet it doesn't check the epoch again, so it's going to go to the queue for the current epoch at https://github.com/libra/libra/blob/dae20021ab2cb806c1daf7a62c06c28ac60ea6f9/consensus/src/chained_bft/network.rs#L432 
6. Select wakes up, and the event-processor of the new epoch handles the message queued a 5, which is actually for the old epoch, at https://github.com/libra/libra/blob/dae20021ab2cb806c1daf7a62c06c28ac60ea6f9/consensus/src/chained_bft/chained_bft_smr.rs#L104

This condition is hard to reproduce, since sometimes, maybe most of the time, 5 will happen before 4, and the message will be first queued, and then cleared.

This could be fixed by simply holding the lock around `EpochInfo` for the duration of each call to one of the `process_` methods in `NetworkTask`, which would prevent the epoch from changing in between the initial `!= self.epoch()` check, and the actual queueing of the message to one of the channel, and that If the epoch changes after the message has been queued, it's not a problem since the queue will be cleared. 

I do think that even if this were to be fixed like this, it's only a matter of time before another similar problems emerges, so I prefer to "larger" solution of https://github.com/libra/libra/pull/2402 which doesn't require accurate locking acrobatics from developers going forward.

**Closed** 2020-04-22 19:25 UTC
Labels: consensus, reconfiguration, techdebt
